- crc-bundle-info.json.sample
- createdisk.sh
- snc.sh
This pull request is on top of #14 
2 of the commits make use of git tags to detect which openshift release we are building for, and adjust a few things accordingly.
The other commits improve the crc-bundle-info.json file to add missing data, the most notable one being the addition of a `nodes` array describing the cluster nodes.
> Metadata improvements

- createdisk.sh
This works around a bug in hyperkit qcow2 implementation on macos which
would cause the whole VM to freeze when it tries to dynamically grow the
qcow2 image
https://github.com/moby/hyperkit/issues/221
Lazy refcounts are a qcow2 performance improvement which should not have
many adverse effects (slower startup in case of improper VM shutdown),
see https://lists.gnu.org/archive/html/qemu-devel/2012-06/msg03827.html
This fixes #38.
https://github.com/code-ready/snc/issues/38
> Enable lazy_refcounts on the qcow2 image we ship

- snc.sh
As of now default ingress operator deployment have 2 replica for
ingress (which provides routing) since in single node cluster second
one is not going to come up and work.
> Issue #44 Scale down the ingress router from 2 to 1.

- snc.sh
On CRC side when a user create a new project/namespace and want to delete,
it goes to hanging state forever. Looking on the kubernetes side and found out
it is occur because of CRD's [0][1], as part of our CRC creation we scale down
the cluster wide monitoring operator[2] which serve 'v1beta1.metrics.k8s.io`.
[0] https://github.com/kubernetes/kubernetes/issues/60807
[1] https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-429754733
[2] https://github.com/code-ready/snc/blob/master/snc.sh#L184-L186
> Issue #54 Delete the v1beta1.metrics.k8s.io apiservice

- createdisk.sh
As of now all the users who are using crc have the same cluster ID which
block us to put our disk images on public side. We are now removing
the cluster ID from the cluster before creating the disk image.
> Issue #61 Remove the clusterID before creating disk image

- createdisk.sh
Right now when a user extract the bundle it finds out there
is a crc_libvirt.sh file and try to execute it which is not
expected from crc side so we should don't include it to the
final tarball.
On the other side this script is nice to do quick testing
on the generated disk image in case any debugging required so
just have it part of source directory.
> Don't include crc_libvirt.sh script to final disk tarball

- 99_master-kubelet-no-taint.yaml
With openshift 4.2 current kubelet unit file which is part of
machineconfig resource need update. On 4.2 nodes by default doesn't
have `crio` service up and running and kubelet unit file now start
it since it have `wants` section. This changes also work with 4.1
since in that case it just get the `crio` already running.
> Issue #66 Update kubelet unit file

- createdisk.sh
- snc.sh
virt-sparsify can be used to create vm disk sparse. It is
reducing around ~700MB disk size and also help us to have
smaller tarball.
> Issue #68 Use virt-sparsify on created qcow2 image.

- createdisk.sh
Installation of hyperV daemons rpms add a new ostree layer which need
to be consumed to get the proper value of vmlinuz, initrd and kernel
cmdline.
> Issue #80 Restart the VM after installing hyperV rpms.

- snc.sh
In CI side this will be useful since we can use single job pipeline
to create the builds for master (in that case unreleased openshift)
and also tagged one.
> Issue 82 Implement to take git tag as argument

- snc.sh
By default ssh public key have user details about whatever user
you are using along with the hostname.
> Use -C option to comment core as user.

- crc-bundle-info.json.sample
- snc.sh
It will be useful to crc to let the user know which version of OpenShift
their cluster is running.
> Add clusterInfo.openshiftVersion to crc-bundle-info.json

- createdisk.sh
virt-sparsify command allow most of the `qemu-img` options
but we can't use it for `--in-place` so need to remove it and
add `lazy_refcounts=on`. This will enable hyperkit to behave
sane when vm is started from stop stage.
>  Issue #84 Add lazy_refcounts option to virt-sparsify cmd

- createdisk.sh
ca1fe612 is now allow to use OPENSHIFT_VERSION environment variable
to run a specific version of openshift. This fix make sure createdisk
also going to use same variable to create directory for artifacts.
> Use OPENSHIFT_VERSION env to specify dest_dir

- createdisk.sh
Due to https://github.com/openshift/installer/pull/1956 , now
by default the location of the qcow2 images are part of
`/var/lib/libvirt/openshift/<cluster_name>_<random_hash>` so
this change will make sure we are copy correct file as part of
our CI.
> Issue #75 Add logic to get qcow2 location for 4.2 cluster

- snc.sh
When running snc.sh, after the cluster started,
we start executing different oc commands for post cluster changes.
Sometime cluster is still not in healthy state and api are not
responding (which need bit more time) and it can fail during execution
of thos oc commands. We should add openshift-install
'wait-for install-complete' just after the run so it can wait till
most of the api are working (mostly give us extra 30 mins).
> Issue #94 Add wait-for command for installer

- createdisk.sh
Server cert is rotated first and then the client one, our check should
validate which is rotated later (client one) to make sure, create disk
operation start after that.
> Use kubelet client cert instead sever to validate expiry time.

- createdisk.sh
Podman and crio both using the CNI networking and that cause the
race condition.
Check https://bugzilla.redhat.com/show_bug.cgi?id=1729603 for detail info.
> Add podman workaround to make it work along with cri-o.

- snc.sh
Right now, we are directly using the quay.io/openshift-release-dev/ocp-release
as hard coded for getting the release information instead of that we should
be making it configurable since nightly release bits comes from
quay.io/openshift-release-dev/ocp-release-nightly registry.
> Issue #102 Get quay registry from environment variable if set

- createdisk.sh
virt-sparsify create `.guestfs-*` as part of sparsify and uses `TMPDIR`.
We use `$destDir` as `TMPDIR` and doesn't remove that config files which
add more data to final tarball.
> Issue #106 Remove `.guestfs-*` directory

- createdisk.sh
~1.5GB data is part of journalctl logs which is part of last run,
better to remove it before creating the bundles.
```
Deleted archived journal /var/log/journal/2567a02e7d8d40ef836b2e565fa8cdd9/system@baf83b88802c423f83b6871da1e0653c-000000000007c5e9-000593920647a0dc.journal (128.0M).
Deleted archived journal /var/log/journal/2567a02e7d8d40ef836b2e565fa8cdd9/system@baf83b88802c423f83b6871da1e0653c-000000000009bad9-00059393e8a944b3.journal (128.0M).
Deleted archived journal /var/log/journal/2567a02e7d8d40ef836b2e565fa8cdd9/system@baf83b88802c423f83b6871da1e0653c-00000000000bafc8-00059395cb7a3919.journal (128.0M).
Deleted archived journal /var/log/journal/2567a02e7d8d40ef836b2e565fa8cdd9/system@baf83b88802c423f83b6871da1e0653c-00000000000da4c3-00059397adb3d626.journal (128.0M).
Deleted …
```
> Issue #109 Remove journalctl logs before generating the bundle.

- registry_pvc.yaml
- snc.sh
Currently `EmptyDir{}` is used as volume for registry which doesn't
able to persist the data from start => stop case.
> Issue #115 Enable PV for registry volume

- .gitignore
- snc.sh
* Changing a check for OPENSHIFT_VERSION variable that works if that
variable isn't declared.
* Changing a git describe to always produce a value.
> Proper Bash check for missing value

- snc.sh
It is possible that sometime client cert is rotated but server one is not or vice versa. We need to add check for both the certs.
```
$ ssh -i id_rsa_crc -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@192.168.126.11 -- sudo openssl x509 -checkend 2160000 -noout -in /var/lib/kubelet/pki/kubelet-client-current.pem
Certificate will not expire
$ ssh -i id_rsa_crc -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@192.168.126.11 -- sudo openssl x509 -checkend 2160000 -noout -in /var/lib/kubelet/pki/kubelet-server-current.pem
Certificate will expire
```
> Issue #117 Validate kubelet server cert also for expiration

- registry_pvc.yaml
- snc.sh
This revert the 7c468bde commit since it is not persist during restart.
To have it properly we need to make the change to configs.imageregistry.operator.openshift.io
resources.
- https://docs.openshift.com/container-platform/4.2/registry/configuring-registry-storage/configuring-registry-storage-baremetal.html
> Issue #115 Add pvc as registry storage.

- kubelet-bootstrap-cred-manager-ds.yaml
- snc.sh
As of now, we need to wait for 24 hour till the kubelet cert rotation
happen, with help of bootstarp cred manager daemon set, it can be rotated
just after the cluster created and new bootstarp csr generated which will
create 30 days valid certs for the kublet client and server.
- https://blog.openshift.com/enabling-openshift-4-clusters-to-stop-and-resume-cluster-vms/
> Issue #27 Force cert rotation after creating the cluster

- snc.sh
From OpenShift 4.3 `TF_VAR_libvirt_master_memory` variable is no
more used to set the master memory, instead now it is implemented as
part of master machineset resource.
- https://github.com/openshift/installer/pull/2399
> Issue #125 update memory/cpu requirement for master node

- snc.sh
Currently, the timeout is 60s which is not enough for kubelet-bootstrap-cred-manager pod
to terminated properly and this also lead to error of deleting the image.
we should increase it to 120s to be in safer side.
```
daemonset.apps "kubelet-bootstrap-cred-manager" deleted
error: timed out waiting for the condition
```
> Issue #127 Increase the timeout for kubelet-bootstrap-cred-manager pod termination

- createdisk.sh
With OpenShift-4.3 the rh-coreos image failed during sparsify because of
the immutable attribute set for /dev/sda4 partition. Need to use guestfish
to remove it and run the virt-sparsify and then apply back.
- https://bugzilla.redhat.com/show_bug.cgi?id=1771257
> Issue #129 Workaround for virt-sparsify to work with immutable partition

- createdisk.sh
We need the image to recover the cert in case it expire, if we don't
tag it properly then we need to do it on the CRC side and that require
the internet connectivity to fetch the hash for KAO image. Now we can
directly use `openshift/cert-recovery` tag without fetching it from the
release payload.
> Issue #131 Tag cluster-kube-apiserver-operator image

- createdisk.sh
For an encrypted disk, virt-filesystem doesn't show all the partition
until specified. Also now there is no `root` label on partition so this logic
need to be changed.
```
$ virt-filesystems -a crc-ssnp7-base -l
Name       Type        VFS   Label       Size       Parent
/dev/sda1  filesystem  ext4  boot        402653184  -
/dev/sda2  filesystem  vfat  EFI-SYSTEM  133169152  -
$ virt-filesystems -a crc-ssnp7-base -l --partitions
Name       Type       MBR  Size         Parent
/dev/sda1  partition  -    402653184    /dev/sda
/dev/sda2  partition  -    133169152    /dev/sda
/dev/sda3  partition  -    1048576      /dev/sda
/dev/sda4  partition  -    16641932800  /dev/sda
```
> Issue #134 Fix partition logic for encrypted partitions

- createdisk.sh
As part of CRC we disable some of operators like (monitoring/machine-config ..etc.) but
the images are always present on the node since there is no knob on installer side right now
to disable those operators from starting (iirc.) Now overall disk size is increases,
till 4.2 our final disk size was around 2GB but with 4.3 it is increasing around 3GB
and that is because all the other images are added as part of CVO payload.
crictl version used in the RHCOS is `0.1.0` which doesn't have fix
for kubernetes-sigs/cri-tools#399 one yet so
using kubernetes-sigs/cri-tools#399 (comment) as workaround.
> Issue #136 Stop generating virtualbox bundle

- createdisk.sh
As part of CRC we disable some of operators like (monitoring/machine-config ..etc.) but
the images are always present on the node since there is no knob on installer side right now
to disable those operators from starting (iirc.) Now overall disk size is increases,
till 4.2 our final disk size was around 2GB but with 4.3 it is increasing around 3GB
and that is because all the other images are added as part of CVO payload.
crictl version used in the RHCOS is `0.1.0` which doesn't have fix
for kubernetes-sigs/cri-tools#399 one yet so
using kubernetes-sigs/cri-tools#399 (comment) as workaround.
> Issue #137 Remove unused images from container storage

- createdisk.sh
Right now during the disk creation `crictl rmp` run just after `crictl stopp`
which fails with following errors if the containers are not stopped properly.
```
$ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i id_rsa_crc core@api.crc.testing -- 'sudo crictl rmp $(sudo crictl pods -q)'
Warning: Permanently added 'api.crc.testing,192.168.126.11' (ECDSA) to the list of known hosts.
time="2019-12-11T05:13:15Z" level=fatal msg="removing the pod sandbox \"8412e11d8371c2d12cc2866db64f5b4678c3a31980d4008c2e0fbeafb1c86b47\" failed: rpc error: code = Unknown desc = failed to remove pod sandbox 8412e11d8371c2d12cc2866db64f5b4678c3a31980d4008c2e0fbeafb1c86b47: unlinkat /var/run/containers/storage/overlay-containers/8412e11d8371c2d12cc2866db64f5b4678c3a31980d4008c2e0fbeafb1c86b47/use …
```
> Issue #139 Add a retry and wait time for `crictl rmp`

- createdisk.sh
podman-remote needs libvarlink-util to be part of VM so it can
able to connect the podman socket running inside the VM.
> Issue #144 Add libvarlink-util package

- snc.sh
So the script doesn't blindly continue if something important like `install cluster` dies.  There may be commands where failure is acceptable, and this change will break those.  You can work around it with:
```sh
command-where-failure-is-ok || echo "this thing failed, but that is ok"
```
I'll leave those off in this commit, because I don't understand this script well enough to know which commands should be allowed to fail.
> snc.sh: Set pipefail, exit on errors and undefined variables

- snc.sh
Add a `MIRROR` variable in case folks want to point at a different mirror for whatever reason.  If neither `OPENSHIFT_VERSION` nor a Git tag are available, use the `latest/` entry on the mirror to fetch the latest release (note that this is not pinned to a particular 4.y, it's just the latest stable release).  Drop `get_openshift_version` and just set up `OPENSHIFT_RELEASE_VERSION` instead; no need to delay that.  Echo the chosen release version and how it was determined to be more transparent and reduce surprise.  Drop empty-`OPENSHIFT_RELEASE_VERSION` checks from the rest of the script, now that `OPENSHIFT_RELEASE_VERSION` is always set.
Pull the release pullspec from the mirror's release.txt for the chosen version.  This decouples us from the Quay tagging scheme ([rhbz#794466][1], …
> snc.sh: Get pullspec from mirrored release.txt

- snc.sh
After deleting a deployment, snc waits for the corresponding pods to be
deleted. If this does not happen quickly enough, it deletes them with
--force. However, in a few cases, the name of the pod to force delete
was not the correct one, this commit fixes that.
> Use correct pod name on forced deletion

- snc.sh
In 4.3.8 looks like the cluster is taking almost full allocated memory
so to start the cluster in sane state we need to increase the memory
resource.
> Update memory from 12GB to 14GB

- crc-bundle-info.json.sample
- createdisk.sh
From 4.4 release etcd certs are now created for
internal IP instead dns srv record like it used to, in case
of the libvirt the internal IP is same as VM ip.
> Add instance IP to metadata

- README.md
I got stuck at building an image without this, and didn't realize that this note was in the wiki.  Adding to make it easier for others to notice.
> Adding a 4.4 workaround note in README.md

- snc.sh
Since now we are using pull secret as file so we don't need to create
a temp file and remove it, temp file creation is removed (7d50e7f) but
rm commands also need to be removed.
> Remove unused rm command from snc script

- snc.sh
Right now `cat` command does show the output of pull secret
in the stdout, using the command grouping we can send all the commands
output in the group to /dev/null which prevent pull secret to show
in the stdout. It also prevent to leak it in the CI environment.
> Hide the pull secret from stdout

- snc.sh
When alternating between running snc.sh and running snc, and rebooting
the machine in between, it's easy to get the host configuration wrong,
and to have the libvirt installer fails after running for an hour or so.
This commit adds checks for the more common mistakes in host
configuration, the only one which is not checked yet is whether the
192.168.126.0/24 network can access the 192.168.122.0/24 network.
This also adds a dependency on xmlstarlet but there is no check for it yet.
This could alternatively probably be handled with a relatively simple go code,
the resulting binary could be automatically downloaded, not sure which way is
best.
> Add preflight checks

- createdisk.sh
In the CI environment we don't really need to validate the cluster
kubelet cert and also current cert rotation method is not work properly
so with this env we can choose to validate or not the cluster certs.
> Add VALID_CERT bool env to validate the cert

- snc.sh
master was pointing to 4.4.x. It's now 4.5.x.
> Pin master to openshift release candidate

- createdisk.sh
Using the threads option for xz we can reduce the bundle creation
time significantly. This will also help us to stop timeout for CI.
```
$ time xz --keep --threads=0 crc.qcow2
real    4m36.255s
user    54m17.698s
sys     0m3.416s
$ time xz --keep crc.qcow2
real    34m48.959s
user    34m46.237s
sys     0m2.710s
$ time xz --threads=0 crc_libvirt_4.4.8.tar
real	15m8.081s
user	107m18.482s
sys	0m18.774s
```
> Use threads option for xz compression

- snc.sh
According to the docs, it's the correct way to scale reduce the number of routers. See https://github.com/openshift/cluster-ingress-operator#managing.
For me, `oc patch` still left a broken pod, `oc scale` correctly remove it.
> Use `oc scale` instead of `oc patch` for scaling down ingress controller

- createdisk.sh
This needs more work on the crc side, let's revert this for now as next
crc release is fairly close.
What does not work:
- Image size is incorrect in the metadata file:
ERRO Invalid bundle disk image '/Users/teuf/.crc/cache/crc_hyperkit_4.5.0-rc.7/crc.img', Expected size 8524267520 Got 33285996544
- crc does not handle correctly sparse files:
$ du -sh ~/.crc/cache/crc_hyperkit_4.5.0-rc.7/
31G    /Users/teuf/.crc/cache/crc_hyperkit_4.5.0-rc.7/
(tar JSxvf ../crc_hyperkit_4.5.0-rc.7.crcbundle uncompresses to a 12G file)
- The machine driver does hardcodes that we are using a qcow2 file
https://github.com/code-ready/machine-driver-hyperkit/blob/master/pkg/hyperkit/driver.go#L228-L234
This reverts commit 8d997d97405b8004cbf1f1a71771a59adf68758e.
> Revert "Use raw image on macos"

- install-config.yaml
- snc.sh
Enable support for both ppc64le and s390x using what’s available from the mirror. Creates a global $ARCH variable and then download proper Openshift binaries from the official mirror. Remove the local arch variable added by preflight check introduced from commit b03abd4. Use proper arch name for yq binary - x86_64 is labeled as amd64.  Also includes the extra step in README to change value of architecture key in install-config.yaml.
@Prashanth684
> Enable Multi-Architecture Support

- snc.sh
We started using candidate for 4.5 because that time latest link
was not available and now it is so switching to latest so our CI
also can test what is comming in latest-4.5 side.
> Update the mirror url to use latest-4.5

- createdisk.sh
This will help us to test the cert rotation effectively since
we can then on the crc codebase side enable it or keep it disabled.
> Disable the network time sync for the bundle

- snc.sh
The current method fails on the installer master.
```
$ oc get csr -oname
certificatesigningrequest.certificates.k8s.io/csr-54rz4
certificatesigningrequest.certificates.k8s.io/csr-7rjpg
certificatesigningrequest.certificates.k8s.io/csr-chcck
certificatesigningrequest.certificates.k8s.io/csr-k88s4
certificatesigningrequest.certificates.k8s.io/csr-pmsqw
$ oc get csr -oname | xargs oc adm certificate approve
No resources found
no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1" in …
```
> Use jsonpath to get the csr resource name

- snc.sh
If user is using older version of oc binary then some of the
functionality doesn't work as expected due to server and client
mismatch.
```
$ oc adm certificate approve csr-chcck
No resources found
error: no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```
> Use oc binary from the payload instead user provided

- snc.sh
This code used to just show an message in case the error was
because of MCo and it is already fixed long time ago and we now
also exit from the script as soon as any command fails.
> Remove unused code

- createdisk.sh
Right now in crc we copy the kubeconfig file from host to VM which
is used to execute oc commands from the VM, this commit will make
sure we do it as part of disk creation so that we don't need to do
it on crc side.
> Copy kubeconfig file to the VM

- snc.sh
Currently our etcd hack function is always running if the snc script
exit before bootstrap, this patch will make sure that as soon as snc
script exit then it's child process also exit (in our case it's etcd hack)
> Kill the child process when main snc process exit

- snc.sh
If the installer fails in the bootstrap process then csr request
is never going to approve but since we are using a loop without timeout
it makes the script to run an infinite loop.
> Add 5 min timeout for csr request

- README.md
- createdisk.sh
- snc.sh
This pull request is to satisfy:
https://github.com/code-ready/crc/issues/977
https://github.com/code-ready/snc/issues/212
* Modified createdisk.sh to allow for overriding the cluster operating system.
* Added docs to README for building SNC for OKD 4
* In createdisk.sh, added a new variable; $BASE_OS which defaults to rhcos. Otherwise, it is can beset to fedora-coreos for disk image logic.
* Added logic for guestfish to be luks aware if OS is rhcos, otherwise it does not assume luks.
To build `snc` for `OKD` you will set the following ENV vars: (For example)
```bash
export OKD_VERSION=4.5.0-0.okd-2020-08-12-020541
export OPENSHIFT_PULL_SECRET_PATH="/tmp/pull_secret.json"
```
The pull secret is fake:
```bash
cat << EOF > /tmp/pull_secret.json
{"auths":{"fake":{"auth": "Zm9vOmJhcgo="}}} …
```
> Enable creating SNC for OKD 4

- cvo_override.yaml
- snc.sh
Node tuning operator is used to tune the node as per workload and
it need tune profile to work and when it updated node needs reboot,
which is not possible for CRC so better to remove the resources
for tihs operator.
> Add CVO override for cluster-node-tuning

- createdisk.sh
Using --sort=name moves crc-bundle-info.json to the first place in the
crcbundle archive. It allows crc and other programs to read the first
bytes of the archive to get the json metadata.
Programs need to read the first ~3KB of the bundle to get the json.
> Make crc-bundle-info.json the first element in the tar archive

- snc.sh
Recently there is an issue with auth operator which was causing
https://bugzilla.redhat.com/show_bug.cgi?id=1874713 one, to avoid
it we need to add unsupported config patch.
- https://github.com/openshift/cluster-authentication-operator/pull/318
> Add auth operator hack to enable single apiserver

- .gitignore
- createdisk.sh
- snc.sh
This decorrelates a little bit more a CodeReady Container version
from an openshift version. `crc` will now have to pick the oc client in
the bundle instead of downloading and adding it in his static
resources.
Relates to https://github.com/code-ready/crc/pull/1511 - it will simplify it.
> Add openshift client oc in the bundle

- README.md
- crc-bundle-info.json.sample
- createdisk.sh
This pull secret can be used to configure the cluster later on. It would
be primarily used by OKD to distribute a good default pull secret.
It can be also used by a large company, where developers are not allowed
to register on cloud.redhat.com to get a pull secret, to internally
distribute the bundle with a pre-defined pull secret. 
cc @cgruver 
Related to https://github.com/code-ready/snc/issues/237
> RFC: Optionally add a default pull secret in the bundle

- snc.sh
In case of unzip is not present on current system install it, like
we are doing for libvirt and other tools
> Install the unzip package if not present

- cvo_override.yaml
- snc.sh
This reverts commit 737d4429f0693effe1301f6aad43919db66b191c.
Looks like it is causing issue for some applications like elastic
search.
- https://github.com/code-ready/crc/issues/1590
> Revert "Add CVO override for cluster-node-tuning"

- snc.sh
On mirror there is always client link which doesn't need version
info which is helpful for scripting part. Right now if we use the
version info then have a `OPENSHIFT_VERSION=candidate` will not
able to download the client binaries since the uri is not correct.
```
curl -L https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/candidate/openshift-client-linux-candidate.tar.gz
+ tar -zx -C openshift-clients/linux oc
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   371  100   371    0     0   2768      0 --:--:-- --:--:-- --:--:--  2768
gzip: stdin: not in gzip format
```
> Remove version info from oc binary download

- createdisk.sh
If the openshift-sdn pods are stop early then crictl not
able to stop any other pods and we see error in the CI around
stopping the pods and then removing it. With this PR we first
get all the pods id which are not openshift-sdn namespace and stop
them first and finally stop the sdn one.
- https://bugzilla.redhat.com/show_bug.cgi?id=1827022
> Fix error for crictl stopp/rmp pods

- createdisk.sh
https://github.com/code-ready/gvisor-tap-vsock/tree/v3
container will not run if a network interface is present.
> Add gvisor-tap-vsock daemon

- createdisk.sh
Since OpenShift 4.4 and crc commit 912ff0ee 'Update certificate recovery
codebase', the 'cert-recovery' image is no longer used.
This reverts commit de4ccd51ec0483f82fc73c8ddead788395665d1f.
> Revert "Tag cluster-kube-apiserver-operator image"

- ci.sh
Extracted from https://github.com/openshift/release/blob/431aac76304a21b1c290811441d8b12b9252450c/ci-operator/step-registry/code-ready/snc/e2e/test/code-ready-snc-e2e-test-commands.sh
This will allow us to define the CI script here instead of defining it in openshift/release repo.
> Add the script run by the CI

- ci.sh
This is required if we want to use ci.sh in all openshift CI jobs, esp. https://github.com/openshift/release/blob/431aac76304a21b1c290811441d8b12b9252450c/ci-operator/step-registry/openshift/e2e/gcp/crc/test/openshift-e2e-gcp-crc-test-commands.sh.
> Destroy the cluster at the end of the CI run

- snc.sh
For ppc64le arch, the default network must be present in order to proceed with the snc install.
If default network is not present, the script will exit. The user should install libvirt-daemon-config-network package.
Closes issue #250
> Check if libvirt default network is present for ppc64le

- createdisk.sh
If we don't wrap '${pods}' with '', the stopp command will only work
for the first pod:
Stopped sandbox fbddcddc0db75c5c5a31bd976a236ef2fac8a1289e43603643d68f799f1aa57c
bash: line 1: ba1001bb7736c6ba475e821a3170a642deb224b371894e580e9eb1ad3a3bee37: command not found
bash: line 2: 3eb6b47dbfe7e8d1ebe42308a8f3fbbcb29492e7a90836c131d34df5e060c087: command not found
> Fix stopping of pods

- cvo_override.yaml
- snc.sh
Unsupported config is used to make etcd work during bootstrap but quorum is
still set to 3 nodes (replica) in the etcd-quorum-guard deployment. In case,
we want to make modification in the CVO override list after crc start then
reconciliation doesn't happen and it throw following error.
```
Error while reconciling 4.6.3: the workload openshift-etcd/etcd-quorum-guard has not yet successfully rolled out
```
With this patch etcd deployment is override to CVO and scale is set to 1 so that
there is no pending pod for quorum.
> BUG 1899459: Delete prometheus validation admission webhook

- crc-bundle-info.json.sample
- createdisk.sh
Currently the name used by crc is the directory name contained in the
crcbundle file. crc also guesses it from the crcbundle file, it takes
the name of the bundle without the extension.
Having a clear name property and the fact that the metadata file can be
read by only extracting the first bytes of the bundle, we can remove
this ambiguity.
> Add bundle name to metadata json

- createdisk.sh
- kubelet-bootstrap-cred-manager-ds.yaml.in
- snc.sh
This reverts commit 4e8dd88e67e5768a3078854e483eaeb171385bf2 and 40fc0b7a3a3277764c5e5655ad154e22909dd792
This is not working as expected and we need to a different supported
way to handle it properly.
> Revert "Use unsupported config map to force the cert rotation"

- crc-bundle-info.json.sample
- snc.sh
The addition of the name property is a new API. Consumers can use the
version field to determine if a name is available or not in the
metadata.
---
Each time we break the compatibility with the previous bundle, we should bump this number.
> Bump version of crc-bundle-info.json file

- createdisk.sh
hv_sock is only loadable when ran under hyper-v. Unconditionnally
loading it causes a warning to be shown when ssh'ing into the VM.
This udev rule will only trigger on hyper-v guests and load hv_sock.
> Replace unconditionnal module loading with udev rule

- .gitignore
- README.md
- crc-bundle-info.json.sample
- createdisk.sh
- snc.sh
io.podman.socket changed to podman.socket for FCOS 33
enable fedora and fedora-updates repos for hyperV driver in FCOS 33
change rsa key to ecdsa for SSH for both FCOS 33 and RHCOS
revolves https://github.com/code-ready/crc/issues/1747 for snc bundle
**Note:** this will break crc builds without: https://github.com/code-ready/crc/pull/1757
> Changes to support OKD 4.6 and change SSH key from RSA to ECDSA

- createdisk.sh
If a variable's value contain the space then only first part of the
value taken by function, better to use double quotes to avoid unwanted
issues.
> Use double quotes for variables which are passed to functions

- ci.sh
- snc-library.sh
- snc.sh
This patch series implements 2 improvements which were suggested
by Miciah in https://bugzilla.redhat.com/show_bug.cgi?id=1868262#c5
There should be no behaviour changes, but snc.sh should be a bit more robust
after these.
> Implement 2 suggestions from rhbz#1868262

- snc.sh
It allows us to remove the export. With that, we clearly know who is
using this variable.
> Explicitly set OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE before calling the installer

- createdisk.sh
Following is current setting for system reserved resource for kubelet
and since we are aiming to developers so removing this can free up some resource.
```
systemReserved:
cpu: 500m
memory: 1Gi
ephemeral-storage: 1Gi
```
> Remove system reserved config block from kubelet

- createdisk.sh
This is a follow-up to 634b37a and to the removal of varlink support
in upstream podman.
> Don't install libvarlink-util on the VM

- snc.sh
With the future routes controller in crc, it would lead to unwanted
hosts file entries since the monitoring is not working.
> Delete routes created by monitoring stack

- ci.sh
- snc.sh
This way of extracting the baremetal installer is also used in the
official docs:
https://docs.openshift.com/container-platform/4.6/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#extracting-the-openshift-installer_ipi-install-installation-workflow
> Extract baremetal installer using a one-liner

- snc-library.sh
Recently created bundle have kubelet certs as expected but the aggregrator
client ca didn't get rotate, this will give some time to rotate that as well
> Add check for aggregrator client ca

- snc.sh
The current code didn't seem to clean up children on exit. Also,
if there were no children to kill, the following error message
showed up on the console:
./snc.sh: line 1: jobs: unbound variable
This fixes both things by:
- replacing TERM with EXIT
- adding a check that 'jobs' is defined before trying to use it
> Clean up child processes more reliably

- install-config.yaml
This was initially changed because it was causing issues when running
crc in an OpenShift cluster.
However the new one causes collisions in a different environment.
Let's try a 3rd different value and see if we are lucky this time :)
I picked:
- an odd number
- bigger than 200
in the hope that sysadmins are less likely to see this as a good value
to use for internal networks.
Note: no problem dropping this if we feel there is no added value :)
> Change clusterNetwork CIDR once more

- snc.sh
Currently the exit code is `0` even snc process is failed
because of `exit 0` as part of trap inline.
```
$ cat test.sh
set -exuo pipefail
trap 'jobs=($(jobs -p)); [ -n "${jobs-}" ] && ((${#jobs})) && kill "${jobs[@]}" || true; exit 0' EXIT
function test_trap() {
while true; do
sleep 3
break
done
echo "This just a check"
}
test_trap &
sleep 4
foobar
$ ./test.sh
./test.sh: line 18: foobar: command not found
+ jobs=($(jobs -p))
++ jobs -p
+ '[' -n 2191906 ']'
+ (( 7 ))
+ kill 2191906
./test.sh: line 1: kill: (2191906) - No such process
+ true
+ exit 0
$ echo $?
0
```
fixes: #312
> Update trap inline to get exit code of the process

- ci.sh
This was helpful because initially we didn't have the way to do
cert rotation instead waiting for 24 hour, which is changed recently
and now it is not required.
commit-id 9155345
> Remove SNC_VALIDATE_CERT env from CI

- createdisk.sh
OpenShift 4.6 added the flag --node-ip in the kubelet systemd unit.
SNC was already adding it at the very beginning. It works most of the
time but I suspect it is just luck and it might fail if the dummy
interface is not ready or so.
This change forces the node-ip to the value we want. The suggested env
file in the kubelet configuration is not working as expected.
I use here the same workaround as the bugzilla 1872632.
Related to https://github.com/code-ready/crc/issues/1888
> Set kubelet node-ip with an environment file

- createdisk-library.sh
Hyperkit and hyper-v directories are generated based on libvirt
directory.
The JSON name was set once, when creating libvirt directory.
> #321 set the correct bundle name for non-libvirt bundles

- createdisk-library.sh
- createdisk.sh
- tools.sh
It's both more efficient space-wise and faster to decompress:
When compressed with `zstd --ultra -22 -T0`, the 4.6.9 bundle is 2.2G in 
size, and uncompresses in about 1 minute. The xz-compressed bundle is 2.6G
in size, and takes 3 minutes to uncompress.
This requires crc-side support: https://github.com/code-ready/crc/pull/1905
> createdisk: Compress bundle using zstd rather than xz

- createdisk-library.sh
- tools.sh
This option will help us to provide different flag for zstd when running
in the CI to generate bundles fast.
> Add CRC_ZSTD_EXTRA_FLAGS env variable to change zstd options for CI

- ci.sh
On openshift CI side the bundle creation takes lot of
time which makes CI to abort due to time out.
> Use different zstd option for CI

- htpasswd_cr.yaml
vs 
"developer" instead of htpasswd_provider
> Make explicit in the console that this login method is for developer

- createdisk-library.sh
- createdisk.sh
- snc-library.sh
- snc.sh
- tools.sh
On most arches, it makes no sense to generate macos and/or Windows bundles.
This commit adds SNC_GENERATE_{MACOS,WINDOWS}_BUNDLE variables which will
only be set x86_64.
> Add SNC_GENERATE_{MACOS,WINDOWS}_BUNDLE

- snc.sh
Now 4.7 is available as candidate better to shift from nightly to
candidate now.
> Shift to 4.7 candidate url instead nightly

- snc.sh
With 4.8, it will use automatically manifests with the annotation
include.release.openshift.io/single-node-developer: "true"
It doesn't change anything for 4.7.
---
If you have good shell advice to refactor that.. I take it!
> Use single-node-developer manifests

- tools.sh
Since RHEL-8.3 now uses libvirtd.socket for service activation, on
the CI side we are observing connection timeout during virsh commands.
```
+ sudo virsh start crc-2ss7l-master-0
error: failed to connect to the hypervisor
error: Cannot recv data: Connection reset by peer
```
> Add retry for virsh commands

- snc.sh
In 4.8 there is no deployment for `etcd-quorum-guard` and it is making
CI to be fail for the master branch of installer.
This can be removed as soon as we branch out 4.7 and use master for the
4.8 side.
> Ignore replica update for etcd-quorum-guard

- snc.sh
- tools.sh
To remove the temp kube:admin user we need to have another user
which have cluster admin role as per documents[0]. This patch is
going to add kubeadmin user and also update the authfile for same.
It will also remove the temp kube:admin user.
[0] https://docs.openshift.com/container-platform/latest/authentication/remove-kubeadmin.html
> Add kubeadmin user as part of htpasswd

- createdisk.sh
- custom-release.json
- snc.sh
Actual usage for memory for these operator is very low. I went
with setting all it to 0 so whatever is required can be taken
from system and more workload can be deployed without memory
outage.
Without this patch (along with monitoring enable)
```
Allocated resources:
(Total limits may be over 100 percent, i.e., overcommitted.)
Resource           Requests       Limits
--------           --------       ------
cpu                2212m (36%)    0 (0%)
memory             11454Mi (73%)  0 (0%)
ephemeral-storage  0 (0%)         0 (0%)
hugepages-1Gi      0 (0%)         0 (0%)
hugepages-2Mi      0 (0%)         0 (0%)
```
After this Patch
```
Allocated resources:
(Total limits may be over 100 percent, i.e., overcommitted.)
Resource           Requests       Limits
--------           -------- …
```
> Remove memory request for all the operator deployments 

- createdisk.sh
It is Observered that in one of the CI run the kubelet.conf file
was empty but then also createdisk process didn't exit because `yq`
doesn't check the key exist during the delete.
fixes: #335
> Add a check for systemReserved key in kubelet

- snc.sh
This will helpful for debuging issue directly getting the logs from
CI run.
> Add must-gather logs in case openshift-install fails

- snc.sh
single-node-developer profile is not part of some of the operators and
we recently noticed that it is causing the issue for dns operator where
openshift/cluster-dns-operator#216 is still not
merged and because of that the dns operator manifest doesn't part of
CVO.
This caused issue for upstream CI and really became hard to debug so
this patch will make sure we don't use any profile and go with default.
- BZ https://bugzilla.redhat.com/show_bug.cgi?id=1940309
> Remove OPENSHIFT_INSTALL_EXPERIMENTAL_CLUSTER_PROFILE env for installer

- snc-library.sh
- snc.sh
With 4.8 we don't require any auth and etcd hack to add unsupported
onfig override, better to remove it from master branch which now
targeted with 4.8 side.
fixes: #374
> Remove auth and etcd hack

- ci.sh
This patch will enable to run k8s conformance tests using the cluster
provision by crc.
> Add k8s conformance tests for CI

- ci.sh
`rsync` is required in case failure occur and we capture the must-gather logs.
```
[must-gather-mlqs2] OUT downloading gather output
WARNING: rsync command not found in path. Please use your package manager to install it.
[must-gather-mlqs2] OUT ./version
```
fixes: #371
> Add rsync package to host machine for CI run

- 99_master-chronyd-mask.yaml
- snc.sh
- Remove 'exit 1' for 'or' bash operator
snc.sh script run with `set -exuo pipefail` which automatic exit as
soon as any command fails so no need to have specific exit for some
commands.
- Update ignition version for chronyd machine config resource
> Minor fixes

- createdisk-library.sh
'PULL_NUMBER' is part of prow job env variables and can be used for
step registry in openshift CI. It will help us to have only latest bundle
for each PR.
- https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#job-environment-variables
fixes: #383
> Use PR number for bundle destination directory

- createdisk-library.sh
- createdisk.sh
Newer OpenShift version (4.7 and newer) no longer use LUKS by default.
OKD does not use it either, so we can remove this code.
This keeps the manual sparsification of the partition for now, as
virt-sparsify failed after a quick try (maybe because / is marked as
immutable?).
> Remove luks support code

- snc.sh
With 4.8 there is no etcd-quorum for single node replica and in the
CI it fails with following so better to remove it.
```
$ oc scale --replicas=1 deployment etcd-quorum-guard -n openshift-etcd
Error from server (NotFound): deployments.apps "etcd-quorum-guard" not found
```
> Remove etcd-quorum-guard deployment resource

- .gitignore
- crc-bundle-info.json.sample
- createdisk-library.sh
- createdisk.sh
Fix https://github.com/code-ready/snc/issues/318
The podman client exactly matches the podman version of the server.
It replicates what we do with oc.
> Add podman-remote binary to bundle

- createdisk.sh
Fixes #396
Master branch on the openshift/installer side uses dev version
of podman which is not available on release pages and this causes
CI failure.
```
INFO[2021-04-19T21:36:44Z] + download_podman 3.0.2-dev
INFO[2021-04-19T21:36:44Z] + local version=3.0.2-dev
INFO[2021-04-19T21:36:44Z] + mkdir -p podman-remote/linux
INFO[2021-04-19T21:36:44Z] + curl -L https://github.com/containers/podman/releases/download/v3.0.2-dev/podman-remote-static.tar.gz
INFO[2021-04-19T21:36:44Z] + tar -zx -C podman-remote/linux podman-remote-static
INFO[2021-04-19T21:36:44Z]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
INFO[2021-04-19T21:36:44Z]                                  Dload  Upload   Total   Spent    Left  Speed
INFO[2021-04-19T21:36:44Z]
0     0    0     0    0 …
```
> Add PODMAN_VERSION env variable for CI

- snc.sh
We are already override the machine config operator so removing those
configs shouldn't affect the cluster and those are regenerated with
updated content as long as user enable it.
> Remove machineconfigs and machineconfigspools

- security-notice.yaml
- snc.sh
Display a banner on top of the console saying this cluster is not for
production usage.
> Add security message on the web console

- login.html.patch
- oauth_cr.yaml
- snc.sh
- tools.sh
When starting the cluster from the tray or when restarting a cluster
after a long time, the user might not remember the credentials.
This message will help him get into the cluster.
(wording, is it secure, etc.. to be discussed :) !)
> Add a tip in login page for getting credentials

- ci.sh
We are seeing lot of failure on the CI because of existing
dnf process.
```
+ sudo yum install -y podman make golang rsync
[...]
Waiting for process with pid 1281 to finish.
```
> Force kill any existing dnf process

- crc-bundle-info.json.sample
- createdisk-library.sh
- test-metadata-generation.sh
Since new `kubeadmin` user is created using `htpasswd` provider and
password is updated for each time when `crc start` happen.
fixes: #414
> Remove kubeadmin-passwd file from the bundle

- ci.sh
This reverts commit 0b1f211314770d4f8206351609a455125fc531ec.
With https://github.com/ironcladlou/openshift4-libvirt-gcp/pull/43
merged, this is no longer needed, and even causes failures when pkill
does not any processes to kill.
> Revert "Force kill any existing dnf process"

- createdisk.sh
- snc.sh
As of now, we are unmasking the chronyd unit file directly using
ssh command so in case of MCO enabled it modify it back again to
masked one so first start of bundle succeed but it fails as soon
as we do stop => start since the crc codebase not able to start
a masked unit.
```
$ systemctl status chronyd.service
● chronyd.service
Loaded: masked (Reason: Unit chronyd.service is masked.)
Active: inactive (dead)
$ sudo timedatectl set-ntp on
Failed to set ntp: Failed to start/stop NTP unit
```
> Disable the chronyd service instead masking it

- createdisk.sh
This patch will make sure the generated bundle have same kind of
property for 4.8 (0beeb25) and 4.7 which is running chronyd service
as default.
> Don't disable the chronyd service

- snc.sh
As part of ae6029b we removed the MCO from override list but missed
this one..
> Don't delete MCO resource for 4.8

- snc.sh
Looks like after the cert rotation
`system:openshift:openshift-authenticator` csr is not recreated and
causing issue for auth operator. As a workaround we need to manually
delete it so new csr is generated with updated cert info.
- https://bugzilla.redhat.com/show_bug.cgi?id=1978193
> Remove the system:openshift:openshift-authenticator csr

- snc.sh
From 4.8 we don't need to scale the deployment because it already
support single node configuration and by default deployment replicas
set to 1.
> Remove replica scale from 2 to 1 for deployment 

- ci.sh
- cvo-overrides-after-first-run.yaml
- cvo-overrides.yaml
- snc-library.sh
- snc.sh
- tools.sh
This patch will fix following error from CI
```
./openshift-clients/linux/oc create -f -
error: error when creating "STDIN": Post "https://api.crc.testing:6443/api/v1/persistentvolumes?fieldManager=kubectl-create": dial tcp 192.168.126.11:6443: connect: connection refused
```
> Add retry for pv creation commands

- createdisk-library.sh
This should fix
```
+ unzip -o -d podman-remote/mac/ podman-remote/mac/podman.zip
Archive:  podman-remote/mac/podman.zip
creating: podman-remote/mac/podman-3.2.3/
+ cp podman-remote/mac/podman crc_hyperkit_461/
cp: cannot stat 'podman-remote/mac/podman': No such file or directory
```
> Use podman-<version> dir to copy podman executable

- createdisk.sh
- snc-library.sh
- snc.sh
- tools.sh
with the developer preview of ARM available for 4.9, adding support in it for SNC so we can work toward having crc support for macs
> support for arm64

- createdisk-library.sh
- snc-library.sh
- snc.sh
In current sceario when we wait for cluster to stable after removing
the pull secret then imagepull error happen for all the marketplace
images since it require the valid pull secret.
```
+ ./openshift-clients/linux/oc get pod --no-headers --all-namespaces
+ grep -v Running
+ grep -v Completed
openshift-marketplace                        certified-operators-n4vlj                                0/1   ImagePullBackOff   0     112m
openshift-marketplace                        community-operators-h5s2d                                0/1   ImagePullBackOff   0     113m
openshift-marketplace                        redhat-marketplace-rm9lm                                 0/1   ImagePullBackOff   0     112m
openshift-marketplace                        redhat-operators-9tqpf …
```
> Compare machine config before and after apply pull secret

- createdisk-library.sh
This reverts commit fe98dd0a449800284484e4b9cdcd2c1776978d50.
4.8.5 is still shipping podman 3.0.1, this move is not needed for the
moment.
Without this, it triggers the following error:
```
+ mv podman-remote/mac/podman-3.0.1/podman podman-remote/mac
mv: cannot stat 'podman-remote/mac/podman-3.0.1/podman': No such file or directory
```
> Revert "Move podman binary from podman-<version> dir to top level dir"

- createdisk-library.sh
Looks like podman 3.2.3 tarball doesn't had executable binary, this
patch will explictly set executable bit.
```
$ curl -L -O https://github.com/containers/podman/releases/download/v3.2.0/podman-remote-static.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   635  100   635    0     0   4471      0 --:--:-- --:--:-- --:--:--  4440
100 14.7M  100 14.7M    0     0  23.7M      0 --:--:-- --:--:-- --:--:-- 23.7M
$ tar -xvf podman-remote-static.tar.gz
$ ll
total 33452
-rw-r--r--. 1 prkumar prkumar 25238888 Jul 16 20:44 podman-remote-static
-rw-rw-r--. 1 prkumar prkumar  9012058 Sep  2 08:51 podman-remote-static.tar.gz
```
> Make podman-remote/podman(mac) binary executable

- createdisk-library.sh
This introduced during 9f73c699f9f53aa26116c19b6713a015ab550fe1 commit
> Fix typo in podman-remote directory

- fcos-config.yaml
user services can't be directly enabled in Butane configs and has
to be manually enabled
ref: https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-user-systemd-unit-on-boot/
> enable podman remote rootless socket

- fcos-config.yaml
This patch add cockpit config related files which force it to put
container view during navigation.
> Force to navigate podman images in cockpit view

- createdisk-library.sh
Without this patch the generated bundle json file looks like following:
```
"fileList": [
null,
{
"name": "podman-remote",
"type": "podman-executable",
"size": "34867234",
"sha256sum": "9cbb0ba547dd989ae64f56053df90ef08579996222d690d0984786c16b95e22b"
}
]
```
Having `null` as first element of list doesn't make sense.
> Fix the filelist index

- createdisk-library.sh
Looks like without this patch when it is used with crc on linux
then after first start the permission on the qcow2 file changes
to following.
```
$ ls -Zl ~/.crc/cache/crc_podman_libvirt_3.4.1/
total 1741452
-rw-rw-r--. 1 prkumar prkumar unconfined_u:object_r:user_home_t:s0        993 Nov 12 11:55 crc-bundle-info.json
-rw-------. 1 qemu    qemu    system_u:object_r:virt_content_t:s0  1748369408 Nov 12 11:55 crc-podman.qcow2
-r--------. 1 prkumar prkumar unconfined_u:object_r:user_home_t:s0        724 Nov 12 11:55 id_ecdsa_crc
-rwxr-xr-x. 1 prkumar prkumar unconfined_u:object_r:user_home_t:s0   34867234 Nov 12 11:55 podman-remote
$ ./crc start -b ~/Downloads/crc_podman_libvirt_3.4.1.crcbundle
[...]
INFO Creating CodeReady Containers VM for Podman 3.4.1...
Error creating machine: Error in …
```
> Update qcow2 image permission from 0600 to 0644

- snc.sh
This reverts commit c1009676b800401cb572062715459da944ddb3d4.
It is fixed upstream so no longer needed.
> Revert "Remove the system:openshift:openshift-authenticator csr"

- snc.sh
By default on the crc side we have default disk size is 31G and for
podman bundle disk resize always run which should be avoided. This
patch will increase it to default size.
If bundle size increase because of this patch then we make the change
in crc side.
- https://github.com/code-ready/crc/issues/2862
> Fix disk size to 31G from 10G

- cvo-overrides-after-first-run.yaml
- cvo-overrides.yaml
Now that the CVO looks at the group property validation and for group
it is different than apiVersion property which required the version
info. This patch drop the version info as part of group.
- https://github.com/openshift/enhancements/pull/982
- https://github.com/openshift/cluster-version-operator/pull/689
> Drop version from 'group' from cvo override

- fcos-config.yaml
In case of user mode networking, vm deployed on windows and linux
have tap interface created which used for packets to send to vsock.
For podman bundles which are based on fedora 35, looks like the dns
server is not set to the tap device and all the query fails because
of it. Also on the f35 coreos image, /etc/resolv.conf is symlinked to
/run/systemd/resolve/stub-resolv.conf, and vm binary shouldn't suppose
to directly modify it.
For a normal interface, what happens is that NetworkManager takes care
of running dhcp requests, and as part of the dhcp request, it receives
DNS details. It's then NetworkManager which takes care of forwarding
this information to systemd-resolved. With current vm binary it runs the
dhcp client.
Follow-up work would be to drop …
> Add dispatcher script for tap device for network manager

- createdisk.sh
- fcos-config.yaml
This patch should enable cockpit to use with bearer token and
make sure only user level service is running.
- https://gist.github.com/gbraad/c556d82394ca0dcc333e9609974fcaf8
It is using https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-user-systemd-unit-on-boot
doc for adding the unit file for core user.
> Add cockpit bearer token script and unit file

- createdisk.sh
This patch remove moby-package from the base layer of the image,
which is not required and might reduce the size of final bundle.
fixes: #496
> Remove moby-engine package from base layer of the image

- fcos-config.yaml
By default zincati service is running which responsible for auto update
of the FCOS host and it always polling the Cincinnati server, this patch
will disable it and rpm-ostree will look like following:
```
$ rpm-ostree status
State: idle
AutomaticUpdatesDriver: Zincati
DriverState: inactive
Deployments:
[...]
```
fixes: #498
> Mask zincati.service for autoupdate

- fcos-config.yaml
This PR helps user to connect docker client from the host to
podman socket in the instance. As of now even with this PR user
have to manually perform following step to test docker client.
```
$ ssh -nNT -L $(pwd)/docker.sock:/var/run/docker.sock -i /Users/prkumar/.ssh/podman-machine-default -p 64940 root@localhost
<-- different terminal -->
$ export DOCKER_HOST=unix://$(pwd)/docker.sock
$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```
This is taken from https://github.com/containers/podman/blob/e06631d6c22f4d5b7a62f70ccdf623379a9d5fe7/pkg/machine/ignition.go#L325-L356
> Enforce a single search registry

- snc-library.sh
${yq_ARCH} is not getting expanded as expected as it is wrapped in ''
> Fix 'arch' setting in crc-bundle-info.json

- createdisk-library.sh
- createdisk.sh
This will try to resolve following error from crc side when downloaded bundle is used.
```
INFO Uncompressing /Users/prkumar/Downloads/crc_podman_hyperkit_3.4.4_amd64.crcbundle
crc-podman.qcow2: 1.64 GiB / 1.64 GiB [------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
Temporary error: rename /Users/prkumar/.crc/cache/tmp-extract/crc_podman_hyperkit_3.4.4_amd64 /Users/prkumar/.crc/cache/crc_podman_hyperkit_3.4.4_amd64: no such file or directory (x12)
```
> [Cherry-pick] Add arch info to directory before compress

- createdisk-library.sh
- createdisk.sh
get_dest_dir can return the full destination directory suffix including
the arch, this is less error-prone this way rather than expecting every
user of destDirSuffix to know yq_ARCH must be appended as well.
> Append arch as part of get_dest_dir

- createdisk-library.sh
For some reason, the code copying id_ecdsa_crc and kubeconfig was not
moved to generate_macos_bundle which is common to hyperkit and vfkit.
This means the vfkit bundles were missing these 2 files.
> vfkit: Add missing files

- createdisk.sh
This reverts commit f4227b5adbd8f237a1f995290eb868f179f3ac3a.
Since https://bugzilla.redhat.com/show_bug.cgi?id=1956739 is now fixed
and available on 4.10.3 onwards.
> Revert "Change the authorized_keys file permission to core user"

- createdisk-library.sh
This should fix following error for new version of qemu packages.
```
qemu-img rebase -b fedora-coreos-qemu.x86_64.qcow2 crc_podman_libvirt_3.4.1/crc-podman.qcow2
qemu-img: Could not change the backing file to 'fedora-coreos-qemu.x86_64.qcow2': backing format must be specified
```
- https://github.com/qemu/qemu/blob/master/docs/about/removed-features.rst#qemu-img-backing-file-without-format-removed-in-61
> Add image format for qemu-rebase

- createdisk-library.sh
- createdisk.sh
From 4.x the name of tarball now includes the arch details and this
PR is to update it.
- https://github.com/containers/podman/releases/tag/v4.0.2
> Podman: Add arch info to podman download URI 

- security-notice.yaml
The old name still appears in the banner displayed at the top of the
OpenShift console https://console-openshift-console.apps-crc.testing
There are still two occurrences of CodeReadyContainers in snc's code:
```
snc.sh:# Add codeReadyContainer as invoker to identify it with telemeter
snc.sh:export OPENSHIFT_INSTALL_INVOKER="codeReadyContainers"
```
Since this is used for installer telemetry, not sure it's wise to change it.
> CodeReady Containers was renamed to OpenShift Local

- snc-library.sh
Some SNC executions fails due to timeout while waiting for the first CSR request, this PR increase the timeout for waiting for the first CSR to 500
> increased timeout  for first csr request to 500

- createdisk-library.sh
The linux static binaries from podman releases 4.0.2 and 4.1.0 available
from github.com/containers/podman are not working:
- the 4.0.2 binary crashes when starting up
- the 4.1.0 binary is a Windows binary instead of being a linux one
The 4.1.1 binary is functional, so this commit temporary hardcodes use
of this version on linux when generating a podman bundle.
> Workaround corrupted podman-remote-linux binaries

- createdisk-library.sh
- createdisk.sh
- snc.sh
This is the PR for the podman branch corresponding to https://github.com/code-ready/snc/pull/534
After it, the only differences between createdisk-library.sh in both branch are
in update_json_description, copy_additional_files, generate_macos_bundle,
generate_hyperv_bundle because they need different files (podman, oc, kubeconfig, ...), and in create_tarball but this difference will be gone when we switch to openshift 4.11 which has podman4
The difference in bundle generation is a bit more complicated to handle in shell, this is why it's not dealt with for now.
> Refactor createdisk-library.sh to make it closer to the one in the master branch

- gen-bundle-image.sh
It will allow user to provide the secret key path as env variable
instead of putting it in the same directory with `gpg_key_pass` name.
> Add env variable for gpg secret key passphrase

- createdisk-library.sh
aarch64 kernels must be uncompressed by the bootloader before booting
them. With the virtualization framework, we won't be using a bootloader,
so we must use an uncompressed kernel.
Uncompressing the kernel can be done directly with gunzip.
> aarch64: Ensure kernel image is uncompressed

- createdisk.sh
snc currently uses
quay.io/crcont/gvisor-tap-vsock:3231aba53905468c22e394493a0debc1a6cc6392
which is not multiarch.
This commit uses the latest tag instead which has both aarch64 and
x86_64 builds.
> [Cherry-pick] Use quay.io/crcont/gvisor-tap-vsock:latest

- install-config.yaml
This reverts commit e4a2d40e6ded085d1d59d4357af62c21e3cce2ed.
During our testing of the bundle with OVN looks like the resource
usage is high for ovn pods than sdn. So during cluster reconcile
it break when using default mem/cpu for crc.
```
Allocated resources:
(Total limits may be over 100 percent, i.e., overcommitted.)
Resource           Requests      Limits
--------           --------      ------
cpu                1990m (52%)   0 (0%)
memory             8480Mi (99%)  0 (0%)
ephemeral-storage  0 (0%)        0 (0%)
hugepages-1Gi      0 (0%)        0 (0%)
hugepages-2Mi      0 (0%)        0 (0%)
```
> Revert "Change network type to OVNKubernetes from OpenshiftSDN"

- snc.sh
This reverts commit c4158a61870825086c5119dd67a37e7797779ed5.
There has been a 0.15.0 butane release with aarch64 payload, so we can
revert this commit as planned:
« When there's a new butane release, we can switch back to using
`release` instead of `latest` »
> Revert "Use `latest` instead of `release` for butane"

- createdisk.sh
This reverts commit 54641afe521c658402df4571d96614d604b5314b.
The related issue ( https://bugzilla.redhat.com/show_bug.cgi?id=1729603
) has been fixed more than 2 years ago in OpenShift 4.4
The initial issue was seen with podman 1.x, recent OpenShift releases
switched to podman 4.x
I don't think this workaround is going to be needed any longer.
> Revert "Add podman workaround to make it work along with cri-o."

- createdisk.sh
- snc-library.sh
- tools.sh
While testing bundle generation on a fresh machine, I had issues with missing libvirt default network, and missing unzip for the macos bundle.
These 2 issues have been fixed in https://github.com/code-ready/snc/pull/503/commits , this PR backports these commits to the master branch
> Backport a few patches from the podman branch

- snc-library.sh
oc 4.11 does not work on macOS, and can cause "certificate is not
trusted" with `oc login` as indicated in OpenShift release notes
https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html
This commit temporarily switches back to oc 4.10 for macOS
This fixes https://github.com/code-ready/snc/issues/576
> Use oc 4.10.x on macOS

- createdisk-library.sh
latest release of podman 4.1.1 and 4.2.0 have correct podman-remote binary so reverting this workaround.
This reverts commit 198c4b5e5df7bb93fbe6da3902a23d1106e82670.
> Revert "Workaround corrupted podman-remote-linux binaries"

- createdisk-library.sh
this package provides utilities for managing mounts
of CIFS network file systems
its needed to make use of windows default  CIFS/SMB
feature for network file sharing between hosts
> Add cifs-utils package to hyperV bundle

- .gitignore
- build-patched-kao-kcmo-images.sh
This script is used by crc dev or internal CI. It suppose to do following
- Get the KAO/KCMO components image from openshift release
- Get the vcs-ref of these component to know their respective dist-git commit ID
- Get the tag of these comonent which used to pull image from brew once it is created.
- Clone the respective comonent from dist-git
- Add it's upstream component as part of git remote and fetch it.
- Merge the vcs-ref of the compnent to rhaos-4.11-rhel-8 branch
- Force push the branch to dist-git
- Create the container build on the brew
- Use skopeo to pull that image from brew and mirror it to quay.io/crcont with all the arch
> Add internal script to build and push KAO/KCMO images

- createdisk-library.sh
In shell $* interpreted as single word so when used with double quote
it make all the word as single one and package installation failed
as following if there is one than one package name.
```
+ install_additional_packages 192.168.13.11 hyperv-daemons cifs-utils
+ local IP=192.168.13.11
+ shift
++ mktemp -d tmp-rpmXXX
+ local pkgDir=tmp-rpmM5Z
+ mkdir -p tmp-rpmM5Z/packages
+ sudo yum download --downloadonly --downloaddir tmp-rpmM5Z/packages 'hyperv-daemons cifs-utils' --resolve
Updating Subscription Management repositories.
Last metadata expiration check: 0:10:30 ago on Friday 30 September 2022 05:48:16 AM UTC.
No package hyperv-daemons cifs-utils available.
Exiting due to strict setting.
Error: No package hyperv-daemons cifs-utils available.
```
> createdisk-library: Use $@ instead $* for package list

- snc-library.sh
Because of https://github.com/code-ready/snc/issues/576 snc is
temporarily hardcoding the use of a 4.10 `oc` version.
However, the URL it's using depends on what `MIRROR` is set to. This can
be a problem if the mirror does not contain a /stable-4.10/ directory.
This commit hardcodes the full URL.
This fixes https://github.com/code-ready/snc/issues/585
> Don't use  for hardcoded mac oc URL

- createdisk-library.sh
This reverts commit 73c7fa1c6ad6ac4e5b5ebaab640722a5e11290e5.
By default rhcos contains the cifs-utils package so no need to add it for hyperV bundle.
```
$ $ cat /etc/os-release
NAME="Red Hat Enterprise Linux CoreOS"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION="411.86.202208291737-0"
VERSION_ID="4.11"
PLATFORM_ID="platform:el8"
[...]
$ rpm -qa | grep cifs
cifs-utils-6.8-3.el8.x86_64
```
> Revert "Add cifs-utils package to hyperV bundle"

- cluster-kube-apiserver-operator.patch
- cluster-kube-controller-manager-operator.patch
- snc-library.sh
- snc.sh
Currently after bootstrap cert rotation, cert validity become 30 days
which is affecting crc users (who start cluster after 30 day). In this
PR we are adding patch to kube-apiserver-operator (KAO) and
kube-controller-manager-operator (KCMO) increase this limit to 1 year.
We are also creating custom release and use that to create cluster
initially.
How to test
-----------
- Update the pull secret file which should have auth for `quay.io/crcont` and `registry.ci.openshift.org` 
To get the credentials for `registry.ci.openshift.org` check https://docs.ci.openshift.org/docs/how-tos/use-registries-in-build-farm/#how-do-i-log-in-to-pull-images-that-require-authentication and the token would be valid for a month https://docs.ci.openshift.org/docs/how-tos/use-registries-in-build-farm/#i-have-logge …
> Add logic to create custom release after patching KAO/KCMO

- kubevirt-hostpath-provisioner-csi/csi-driver-hostpath-provisioner.yaml
- kubevirt-hostpath-provisioner-csi/csi-kubevirt-hostpath-provisioner.yaml
- kubevirt-hostpath-provisioner-csi/csi-sc.yaml
- kubevirt-hostpath-provisioner-csi/external-health-monitor-rbac.yaml
- kubevirt-hostpath-provisioner-csi/external-provisioner-rbac.yaml
- kubevirt-hostpath-provisioner-csi/kubevirt-hostpath-security-constraints-csi.yaml
- kubevirt-hostpath-provisioner-csi/namespace.yaml
- registry_pvc.yaml
- snc-library.sh
- snc.sh
this sets up dynamic provisioner for pvs backed by
hosts's filesystem
the CSI driver is part of the kubevirt project and
the manifests used are available in their repo at:
https://github.com/kubevirt/hostpath-provisioner/tree/main/deploy/csi
this also modifies the pvc manifest for the internal registry
to set the StorageClass that uses the CSI based provisioner
when creating new pvc one should use the storageClassName
"crc-csi-hostpath-provisioner"
Fixes #444
> Setup kubevirt-hostpath-provisioner

- createdisk-library.sh
- createdisk.sh
- qemu-guest-agent.service
- qemuga-vsock.te
This will be needed by the timesync code (set the VM time automatically when the machine gets out of sleep).
> podman: Install qemu-guest-agent in the bundle

- kubevirt-hostpath-provisioner-csi/csi-driver/kustomization.yaml
Downsteam image for hostpath-csi-driver does have image for arm64. we will revert back once it is available downstream.
> Remove downstream image for hostpath-csi-driver

- kubevirt-hostpath-provisioner-csi/csi-driver-hostpath-provisioner.yaml
File is the correct policy to use in our case, which allows the volumes file permissions to match the requested permissions from the pod
CSIDriver docs: https://kubernetes-csi.github.io/docs/csi-driver-object.html
this fixes the following permission denied error in the image registry pod when trying to mirror images
```
level=error msg="response completed with error" err.code=unknown err.detail="filesystem: mkdir /registry/docker: permission denied"
```
> Set fsGroupPolicy to File for hostpath-provisioner CSIDriver

- build-patched-kao-kcmo-images.sh
This would fix following error and `AOS Automation Release Team` have it also for each commit downstream.
```
remote: Adding big files into git is bad. Once they are committed, they can not be removed and will have to be downloaded with each new clone.
remote: Please use "rhpkg upload" to put the files into lookaside cache and "rhpkg sources" to download them again.
remote: If you are absolutely sure you want to commit it, you can override the limit in your commit message by adding the following line. The size is in bytes.
remote:     - MaxFileSize: 123456
remote: Alternatively contact EXD SP to adjust the limit for this repository via
remote:   https://hurl.corp.redhat.com/sp-ticket
To ssh://pkgs.devel.redhat.com/containers/crc-cluster-kube-apiserver-operator
! [remote rejected]   HEAD …
```
> build-patched-kao-kcmo-images: Add maxsize for merge commit

- createdisk.sh
Most of the time during testing when we regenerate the bundle it fails because same version of bundle directory and bundle file exists. This PR first remove this directory/file before moving to next step.
> Remove bundle and bundle dir before creating it

- createdisk-library.sh
I forgot to remove a restorecon call after adding the `-Z` flag to the
`mv` call just before it.
> qemu-ga: Remove left-over commented out line

- createdisk-library.sh
- createdisk.sh
- qemu-guest-agent.service
- qemuga-vsock.te
It will be used to sync the time of the guest on macOS when the system gets out of sleep.
A selinux policy change is needed to be allowed to use it over virtio-vsock.
To apply it (
https://relativkreativ.at/articles/how-to-compile-a-selinux-policy-package )
checkmodule -M -m -o qemuga-vsock.mod qemuga-vsock.te semodule_package -o qemuga-vsock.pp -m qemuga-vsock.mod semodule -i qemuga-vsock.pp
> Install qemu-guest-agent in the bundle

- createdisk-library.sh
the version of selinux policy kit where the package is built should be the same in the target machine where the package is installed in our case the host where we are building is rhel9 and the targets os is rhel8, where it fails to install with the following error:
```
libsemanage.semanage_pipe_data: Child process /usr/libexec/selinux/hll/pp failed with code: 255. (No such file or directory).
qemuga-vsock: libsepol.policydb_read: policydb module version 20 does not match my version range 4-19
qemuga-vsock: libsepol.sepol_module_package_read: invalid module in module package (at section 0)
qemuga-vsock: Failed to read policy package
libsemanage.semanage_direct_commit: Failed to compile hll files into cil files.
(No such file or directory).
semodule:  Failed!
```
> build qemu-ga selinux policy package inside the guest

- snc.sh
Right now we are removing the machineconfig which is generated after pull secret changes happen and machine config operator fails to reconcile in case of openshift-4.12 because as soon as we delete the pull secret it is not able to pull image to inspect the content which is added
- https://github.com/openshift/machine-config-operator/commit/1671a453f1a95ff9e3720719c4151f289e2fdd0c
```
I1123 10:31:08.119905    4150 run.go:19] Running: podman pull -q --authfile /var/lib/kubelet/config.json quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ffa3568233298408421ff7da60e5c594fb63b2551c6ab53843eb51c8cf6838ba
Error: initializing source docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ffa3568233298408421ff7da60e5c594fb63b2551c6ab53843eb51c8cf6838ba: reading manifest …
```
> Remove render machine config which have pull secret info

- createdisk.sh
- snc.sh
Trying to generate a podman bundle on rhel8 currently fails early when trying to read the selinux context of crc-tmp-install-data. This commit fixes that along with 2 other small cleanups.
> Minor podman bundle generation fixes/improvements

- createdisk-library.sh
RHEL8 only supports policy modules up to version 19, while fedora and rhel9
use newer versions. When building on the host, we need to make sure the
policy module we build is compatible with rhel8 which is what the openshift
bundles use as a base OS.
> qemuga: Ensure selinux policy module is rhel8-compatible

- snc-library.sh
As of now we first approve the first pending csr for
kube-apiserver-client-kubelet and then approve kubelet-serving one.
On the CI it is observed that as soon as we approve kube-apiserver-client-kubelet
csr (csr-qc8c7), another one is create with same signer name (csr-c28jv) and kubelet-serving not
created until this one is also approved.
```
$ oc get csr
NAME                                             AGE     SIGNERNAME                                    REQUESTOR                                                                         REQUESTEDDURATION   CONDITION
csr-b4gb2                                        24h     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper         <none>              Approved,Issued …
```
> Misc changes for cert approval and validating

- snc.sh
We are not sure at what time apiserver became unavailable or goes to reconcile state. This patch add retry function in case first time command execution not successful and fix following issue which occur time to time on the CI
```
+ ./openshift-clients/linux/oc get mc --sort-by=.metadata.creationTimestamp --no-headers -oname
+ grep rendered-master
+ head -n -2
+ xargs -t ./openshift-clients/linux/oc delete
./openshift-clients/linux/oc delete
error: You must provide one or more resources by argument or filename.
```
> Add retry to get machine config in case apiserver not respond at first

- snc.sh
We are not sure at what time apiserver became unavailable or goes to reconcile state. This patch add retry function in case first time command execution not successful and fix following issue which occur time to time on the CI
```
+ ./openshift-clients/linux/oc get mc --sort-by=.metadata.creationTimestamp --no-headers -oname
+ grep rendered-master
+ head -n -2
+ xargs -t ./openshift-clients/linux/oc delete
./openshift-clients/linux/oc delete
error: You must provide one or more resources by argument or filename.
```
> [release-4.12] Add retry to get machine config in case apiserver not respond at first

- build-patched-kao-kcmo-images.sh
- snc-library.sh
- snc.sh
This PR adds 2 new features to the script:
- it automatically regenerates crc-dnsmasq and crc-routes-controller so that they use the same base image as the rest of the cluster
- it builds a patched release image so that it's only done once
> build-patched-kao-kcmo-images.sh improvements

- createdisk-library.sh
- createdisk.sh
Because of https://github.com/crc-org/vfkit/issues/11 we need to use an 
older kernel with our macOS bundles. This is fixed in macOS 13, but we want
to keep compatibility with macOS 12 for a while.
However, we want to keep using the latest kernel for linux and Windows.
This PR starts by refactoring the bundle generation. Before this PR, the bundle generation process is roughly:
- do various modifications in the VM
- shut down the VM
- use the same VM image for all 3 platforms
After this PR, it will become:
- do various modifications in the VM
- shut it down
- generate the linux/Windows bundles
- restart the VM
- downgrade the kernel
- shut the VM down
- generate the macOS bundle
This makes the bundle generation slower as making the VM image
sparse/converting it/... can be slow, but this …
> macos: Install older kernel

- cvo-overrides-after-first-run.yaml
Since we are using the capabilites now and it is missed during f6d417c commit.
> Remove csi-snapshot-controller-operator from CVO override

- snc.sh
This reverts commit 791d8e2cda8042c7fa0ff81187aab6df3b1f46d7.
It is now fixed and available in 4.12.3 and 4.13.0-ec.3
- https://github.com/openshift/machine-config-operator/pull/3526
> Revert "Remove render machine config which have pull secret info"

- createdisk-library.sh
podman-remote linux binary now have arch info and binary is placed under bin folder before creating the tarball. We now need to extract it with bin folder and remove it after moving it to correct location.
```
$ curl -L -O https://github.com/containers/podman/releases/download/v4.4.1/podman-remote-static-linux_amd64.tar.gz
$ tar -tf podman-remote-static-linux_amd64.tar.gz
./bin/podman-remote-static-linux_amd64
```
fix #662
> Fix podman static binary for linux which now have arch info

- kubevirt-hostpath-provisioner-csi/csi-driver/csi-kubevirt-hostpath-provisioner.yaml
- kubevirt-hostpath-provisioner-csi/csi-driver/kustomization.yaml
the community kubrenetes registry will be depreceted and is replace with registry.k8s.io more details in https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
> replace k8s.gcr.io with registry.k8s.io

- snc.sh
This will create the currect registry-certs configmap incase the user changed the default SNC_PRODUCT_NAME or BASE_DOMAIN
> Use ${SNC_PRODUCT_NAME}.${BASE_DOMAIN} instead of crc.testing

- createdisk.sh
It was by mistake added during 9bd725ca9ede737e1c98a8c42702bb88bcfa7d64 where it should be the config.yaml
> Should use config.yaml instead config.yaml.default

- podman_changes.ks
With https://github.com/containers/common/commit/0db57c8ff1272546f13100d464674366d98323a9 `machine_enabled=true/false` setting in the containers.conf is deprecated and now there is `podman-machine` marker file, which is used for this setting.
- https://github.com/containers/common/blob/main/pkg/machine/machine.go#L21
> Use podman machine marker instead deprecated enabled machine config

- createdisk-library.sh
Its path in the archive changed again with the 4.4.2 release which
landed in FCOS 37.20230322.3.0 stable
> podman: Fix extraction of podman 4.4.2 binary

- createdisk.sh
Looks like till 4.12 the podman.socket enabled by default for the user because it is vendor `preset: enabled` so when this package is installed it is enabled by default but it is not case for 4.13
4.12 bundle side
```
$ systemctl --user status podman.socket
● podman.socket - Podman API Socket
Loaded: loaded (/usr/lib/systemd/user/podman.socket; enabled; vendor preset: enabled)
Active: active (listening) since Fri 2023-03-31 15:37:43 UTC; 1min 41s ago
Docs: man:podman-system-service(1)
Listen: /run/user/1000/podman/podman.sock (Stream)
CGroup: /user.slice/user-1000.slice/user@1000.service/podman.socket
```
4.13 bundle side (which is based on RHEL-9)
```
$ systemctl --user status podman.socket
○ podman.socket - Podman API Socket
Loaded: loaded (/usr/lib/systemd/user/podman.socket; disabled; …
```
> Enable podman service for user level

- ci_microshift.sh
This was re-added in the commit introducing ci_microshift.sh in spite of being pointed out during PR review.
> Stop using github.com/code-ready/crc

- snc-library.sh
This reverts commit a5d8d95494cf0c8c65c57036e5b6f0efeee983d4.
https://bugzilla.redhat.com/show_bug.cgi?id=2097830 is now
fixed. It is available >=4.12.13 which is already in latest channel now.
> Revert "Use oc 4.10.x on macOS"

- build-patched-kao-kcmo-images.sh
As of now we use `MIRROR` which can be changed using this env variable or it has default value but then we have a local mirror where we want to create custom images for different arch and for that we are again using `mirror` local variable which need to updated. With this PR we just use `MIRROR` variable and consume it both the place.
> build-patch-script: Update the arch info using sed instead duplicate

- createdisk-library.sh
This currently fails with dependency issues related to 
missing kernel-uname-r dependencies. 
This PR should fix that. During my testing, first try failed, and second
attempt succeeded, so this must go through CI first :)
Fixes: https://github.com/crc-org/snc/issues/700
> podman: Fix kernel downgrade

- ci.sh
This PR make sure we run the podman bundles which is created
by CI using crc. It will make sure produced bundles are able to
run without any issue.
> CI: Run podman bundle with crc

- createdisk-library.sh
This reverts commit 4ccff2c48cec40217cfbc082af05b2f865402cec.
fixes #707 they are going to have the dir structure always containing the podman binary inside a bin/ dir
> Revert "podman: Fix extraction of podman 4.4.2 binary"

- microshift.sh
By default `cloud-utils-growpart` package is not installed which provides `growpart` cli tool to resize the disk image. This pr add that package to image builder blueprint to have it part of generated bundle.
> Microshift: Add growpart package to image builder blueprint

- createdisk-library.sh
It will make sure in single command unwanted package is removed and required packages are replaced.
```
$ rpm-ostree override replace -h
Usage:
rpm-ostree override replace [OPTION…] PACKAGE [PACKAGE...]
Replace packages in the base layer
Help Options:
-h, --help            Show help options
Application Options:
--remove=PKG          Remove a package
[...]
```
> downgrade_kernel: Use --remove=PKG option of rpm-ostree replace command

- createdisk.sh
Most of the images are not yet available for all the platform and majority of those are x86_64 arch. Redhat doesn't have `qemu-user-static` package[0] but for developer usecase it is good to support it even a non supported way.
[0] https://access.redhat.com/solutions/5654221
> Add qemu-user-static-x86 package from fedora koji

- createdisk-library.sh
- createdisk.sh
Because of https://github.com/crc-org/vfkit/issues/11 we need to use an older kernel with our macOS bundles.
This is fixed in macOS 13, but we want to keep compatibility with macOS 12 for a while.
This uses the kernel which is part of RHEL-9.0 by replacing 9.2 kernel.
> Issue 711 - macos: Install older kernel

- createdisk-library.sh
Older version of kernel doesn't have `kernel-modules-core` package which we want to downgrade to so when we are replacing the kernel packages, following error occur.
```
$ SYSTEMD_OFFLINE=1 sudo -E rpm-ostree override replace /home/core/packages/*.rpm
Warning: Permanently added '192.168.126.11' (ECDSA) to the list of known hosts.
Running in chroot, ignoring command 'start'
Checking out tree 022b802...done
No enabled rpm-md repositories.
Importing rpm-md...done
Resolving dependencies...done
␛[0m␛[31merror: ␛[0mCould not depsolve transaction; 1 problem detected:
Problem: package kernel-modules-core-5.14.0-284.13.1.el9_2.x86_64 requires kernel-uname-r = 5.14.0-284.13.1.el9_2.x86_64, but none of the providers can be installed
- cannot install both kernel-core-5.14.0-70.53.1.el9_0.x86_64 and …
```
> Remove kernel-modules-core package to avoid conflict

- createdisk.sh
We added regression 68c6383de78d658b2581fb0f5097dbf34618befc for OKD bundle since we never downgrade kernel for OKD even in case of 4.12 side and OKD always used fedora as base.
During internal discussion we are not sure how many folks are consuming OKD on mac since there is no arm64 support and no bug/issue reported for OKD on mac due to https://github.com/crc-org/vfkit/issues/11.
With this PR we are still not downgrading kernel and if there is some user issue/feedback we will ask community to put a patch for it given that we already have logic in `podman` branch.
> createdisk: Don't downgrade kernel in case of OKD bundle

- build-patched-kao-kcmo-images.sh
- snc.sh
4.14 is in dev phase so mirror url changed to `ocp-dev-preview`
> Update mirror url for 4.14 candidate bits

- snc.sh
This was still using ocp-dev-preview, but since 4.13 is released,
ocp-dev-preview is no longer needed/updated.
> snc: Switch to https://mirror.openshift.com/pub/openshift-v4/$ARCH/clients/ocp/

- microshift.sh
podman requires a container runtime, and networking plugins to work.
They are only marked as Recommends/Suggests in podman's spec file, so we
need to ensure they get installed.
commit 14fdeea installs these explicitly, but podman's spec file
recommends `crun` and not `runc`, no idea if these are the same or not.
Better to rely on what podman .spec file provides rather than hardcoding
it.
> microshift: Install weak deps when installing podman

- createdisk.sh
As of now this file contain the device name and disk ID associated with a physical volume identifier (PVI) and we noticed that device name is different for different hypervisor like for hyperV it is `/dev/sda` and for libvirt it is `/dev/vda` [0].
In this PR we follow `man lvmdevices` which states remove of this file means lvm will not use a devices file.
```
The  LVM  devices file lists devices that lvm can use.
The default file is /etc/lvm/devices/system.devices, and
the lvmdevices(8) command is used to add or remove device
entries.  If the file does not exist, or if lvm.conf includes
use_devicesfile=0, then lvm will not use a devices file.
```
With this patch I don't see any degrade in boot time
```
<=== with the patch ===>
INFO CRC instance is running with IP 127.0.0.1
INFO CRC VM is …
```
> Remove lvm system device file

- createdisk.sh
- route_controller.yaml.in
This PR adds deployment resource for route controller which use correct image tag, what we cached. Once the bundle is created using this PR, we will also need to make change on crc side. The resource file is located in `/opt` dir same as `kubeconfig` file.
> Add route controller resource to bundle

- kubevirt-hostpath-provisioner-csi/csi-driver/kustomization.yaml
We now have arm64/amd64 images for hostpath-csi-driver and no need to build it on internal brew and putting on `quay.io/crcont`.
> Use hostpath-csi-driver image from registry.io

- createdisk-library.sh
- createdisk.sh
During microshift bundle creation d90d53d22d51fdf406e265ac964206f46d2badd0 we created `sparsify_lvm` to move fast to have microshift bundle sooner. With this PR we are going to use sparsify helper for microshift bundle and remove the `sparsify_lvm` helper.
> Createdisk: update sparsify helper to use for microshift bundle also

- createdisk-library.sh
- createdisk.sh
68c6383 moved the kernel changes from an aarch64-only block to a block which is run when the macOS bundle is enabled. However, the kernel downgrade is done before any bundle is generated, so the kernel will be downgraded for all our bundles, linux, macos, windows.
This PR fixes this and use https://github.com/crc-org/snc/pull/637 logic to only downgrade the kernel for macOS.
> Downgrade kernel only for mac

- microshift.sh
microshift is officially released in RH repos, and microshift.sh already requires a subscription, so we can use `yum download` instead of `brew download-build`.
I've checked that setting `MICROSHIFT_NVR` works for 4.13 releases.
> microshift: Drop RH internal 'brew' requirement

- snc-library.sh
openshift/okd bundles use `qemu+tcp` connection so that doesn't need the 'sudo' to get the details about network, uri and capabilities but for microshift bundle we use same preflight checks and use `qemu:///system` uri which need `sudo` to get those details otherwise the CI fails with following error:
```
+ '[' microshift == okd ']'
+ virsh -c qemu:///system uri
error: failed to connect to the hypervisor
```
> Use sudo for virsh commands as part of preflight checks

- createdisk.sh
For microshift bundle creation `VM_PREFIX` is not set and CI have following error. This PR add `microshift` as default value in case there is no value set.
```
./createdisk.sh: line 157: VM_PREFIX: unbound variable
```
> Use microshift as default value if VM_PREFIX is not set

- ci_microshift.sh
We need to remove the crc domain which is created as part of bundle creation process otherwise we are not able to test the this bundle with `crc` binary which also want to create same domain and fails with following error
```
level=info msg="Creating CRC VM for MicroShift 4.13.4..."
Error creating machine: Error in driver during machine creation: virError(Code=9, Domain=20, Message='operation failed: domain 'crc' already exists with uuid 5ab0edb0-4c93-484f-8563-a91529d467ba')
```
> ci_microshift: Remove crc domain after bundle creation

- install-config.yaml
From 4.14 MachineAPI is part of capability and we need to explict enabled it.
- https://pkg.go.dev/github.com/openshift/api/config/v1#ClusterVersionCapability
> [release-4.14]Install-config: Add MachineAPI to enable as part of capability

- snc.sh
Recently we found out that due to mcp is not in updated state, created bundles had issue with machine config like following
```
Marking Degraded due to: machineconfig.machineconfiguration.openshift.io "rendered-master-5e0b4b6fd5ad9c5c64801e18039b9233" not found
```
when the mcp is not updated properly
```
$ oc get mcp
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master   rendered-master-5e0b4b6fd5ad9c5c64801e18039b9233   False     True       True       1              0                   0                     1                      3d13h
worker   rendered-worker-e6687df4c217440327c4dc1dcf0f507c   True      False      False      0              0 …
```
> Wait till machine config pool is in updated state

- gen-bundle-image.sh
This PR refactor around set_bundle_variables, generate_image and sign_bundle_files functions to make sure image can be generated for microshift bundle also.
> gen-bundle-image: refactor to accomodate microshift preset

- gen-bundle-image.sh
It was missed during 491351665a6590bb434fb761372d1915a413ab3d one.
> gen-bundle-image: allow to build arm64 image for microshift also

- snc-library.sh
In microshift we don't configure app route different than base domain like we can do in OCP using ingress configuration, so app route for microshift become `apps.crc.testing` but for OCP it is `apps-crc.testing`. This patch make sure it is updated to the bundle metadata correctly.
> snc-library: Fix app route for microshift preset

- build-patched-kao-kcmo-images.sh
Looks like internally [0] anonymous operations are changed from `git` to `https` because git protocol miss encryption.
[0] https://issues.redhat.com/browse/RHELBLD-10855
should fix
```
git remote add upstream git://pkgs.devel.redhat.com/containers/ose-cluster-kube-apiserver-operator
+ git fetch upstream rhaos-4.14-rhel-8 --no-tags
fatal: unable to connect to pkgs.devel.redhat.com:
pkgs.devel.redhat.com[0: x.x.x.x]: errno=No route to host
```
> build-patched-kao-kcmo-images.sh: Use https instead of git for encryption

- ci_microshift.sh
- microshift.sh
This PR adds `clearpart` option `--disklabel` to use `gpt` as default disk label and to allow this we also need to add a partition of `biosboot` so that it will not error out with following error.
```
your bios-based system needs a special partition to boot from a gpt disk label
```
- https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#clearpart
- https://access.redhat.com/solutions/3370891
> Use GPT partition table instead msdos

- install-config.yaml
4.14 add more capability like image-registry, build and deployment as addon which can be added on top of `None`. By default since we are using `None` those capabilities need to be added explicitly to have it part of cluster since we are providing these features before.
> install-config.yaml: Add image-registry, build and deployment config capability

- build-patched-kao-kcmo-images.sh
- install-config.yaml
- microshift.sh
- snc.sh
Merge release_4.14 branch to master, there is some conflicts which resolved manually and microshift script changes https://github.com/crc-org/snc/pull/811/commits/e6e743cf246bdd870e405958d698c287a78d47b9 one.
> Merge release_4.14 to master 

- createdisk.sh
Till 4.13 `basedomain` string was commented[0] but with 4.14 looks like it is not commented anymore and default basedomain used as `example.com`
[0] https://github.com/openshift/microshift/blob/release-4.13/packaging/microshift/config.yaml#L3
[1] https://github.com/openshift/microshift/blob/release-4.14/packaging/microshift/config.yaml#L16
> createdisk: fix basedomain regex

- microshift.sh
Time synchronization on macOS relies on qemu guest agent being present, and snc enables a qemu-guest-agent systemd service, which fails to start since the qemu-guest-agent is not installed (more specifically, the unit file created by snc expects /etc/sysconfig/qemu-ga to exist, this is installed by the qemu-guest-agent package)
> Microshift: Add qemu-guest-agent package

- install-config.yaml
With 4.15 OperatorLifecycleManager become dependency of marketplace capability. 
This will fix following error
```
failed to create install config: invalid "install-config.yaml" file: additionalEnabledCapabilities: Invalid value: []v1.ClusterVersionCapability{"openshift-samples", "marketplace", "Console", "MachineAPI", "ImageRegistry", "DeploymentConfig", "Build"}: the marketplace capability requires the OperatorLifecycleManager capability
```
- https://pkg.go.dev/github.com/openshift/api/config/v1#ClusterVersionCapabilitySet4_15
> Add OperatorLifecycleManager as part of enabled capability

- createdisk-library.sh
The kernel we used so far was from October 2022, which is unexpected, we
intended to pick up the latest 9.0.z kernel.
This hardcodes the kernel version to the latest 9.0.z kernel released as
of today, need to find a better way to get this...
This fixes https://github.com/crc-org/snc/issues/826
This also fixes macOS x86_64 microshift bundles which fail to boot
without this. The kernel modules can't be loaded.
> Use latest released rhel-9.0.z kernel

- createdisk-library.sh
to install the latest rhel-9 kernel we need to use the rhel-9-for-aarch64-baseos-eus-rpms for arm64 and for amd64 the rhel-9-for-x86_64-baseos-eus-rpms repo
this makes use of the ${ARCH} variable to form the repo id
> use arch specific repository id for kernel package

- createdisk-library.sh
https://issues.redhat.com/browse/OCPBUGS-11437 is now fixed which means we no longer need to use the workaround to update .orig file of pull secret to have it replace with a dummy one.
> Remove hack around MCO .orig file

- build-patched-kao-kcmo-images.sh
- createdisk.sh
Right now we use crc-dnsmasq container to provide the dns service for different `.testing` subdomain locally and till now it worked as expected when we were using the openshift-sdn but with OVN-K it is not going to work because this container use new podman bridge and we have fix IP address `10.88.0.8` for it. In case of of OVN-K this IP is not resolvable by dns pod of openshift and dns resolution for those `.testing` subdomain going to fail.
With this removal we need to adjust the code on crc side to put the configuration to VM dnsmasq service and use it.
```
=== using openshift-sdn ===
$ oc rsh busybox-sleep-pod
sh-5.1# ping 10.88.0.8
PING 10.88.0.8 (10.88.0.8) 56(84) bytes of data.
64 bytes from 10.88.0.8: icmp_seq=1 ttl=63 time=0.878 ms
64 bytes from 10.88.0.8: icmp_seq=2 ttl=63 …
```
> Remove crc-dnsmasq container and run dnsmasq directly on vm

- createdisk-library.sh
- createdisk.sh
- snc-library.sh
- snc.sh
Since `okd-scos` is better upstream for OCP than FCOS one. It also have pre-release version of 4.15 so switching OKD bundles to it.
- https://github.com/okd-project/okd-scos
> Move OKD bundle from FCOS to SCOS

- install-config.yaml
From 4.15 CloudCredential is not part of core capability and it should be enabled if the cluster is not provision on baremetal (we are using libvirt provider).
- https://github.com/openshift/api/blob/2054c69227a1/config/v1/types_cluster_version.go#L488-L503
As part of libvirt provider we really don't need it and removing is as part of cvo-override.
This pr will fix following issue as part of snc run.
```
+ ./openshift-baremetal-install --dir crc-tmp-install-data create manifests
level=error msg=failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: invalid "install-config.yaml" file: capabilities: Invalid value: types.Capabilities{BaselineCapabilitySet:"None", AdditionalEnabledCapabilities:[]v1.ClusterVersionCapability{"openshift-samples", …
```
> install-config: Add CloudCredential capability to enabled capabilities

- microshift.sh
Currently `MICROSHIFT_PRERELEASE` is broken because for a unreleased version of microshift there might be already branch which is not track with `main` (eg. release-4.15) and bits are part of `ocp` instead of `ocp-dev-preview`. It happens when a specific openshift/microshift release goes to rc from ec. With this PR we are only using `MICROSHIFT_PRERELEASE` for download packages and
`MICROSHIFT_BRANCH` is used to track the branch info for microshift.
> microshift: Add `OPENSHIFT_MINOR_VERSION` env variable to track branch

- snc-library.sh
Looks like there is confusion around the oc download path url to grab platfrom specific binary. Ideally if we use arch specific url to download the oc binary it should have by default for that specific org which is not the case so need to explicit specify the arch info in the url.
- https://issues.redhat.com/browse/OCPBUGS-28720
> Update oc binary download url for arm64 binary

- kubevirt-hostpath-provisioner-csi/csi-sc.yaml
this restore to the original behavior we had for persistent volumes when they were manually created and had reclaimPolicy as Recycle
with this pvs dynamically created by the hostpath-provisioner won't be deleted allowing users to recover any data after deleting a pod/pv
fixes #835
> Change reclaim policy of default storage class to Retain

- README.md
- snc-library.sh
As part of libvirt IPI installation, it was required to have tcp socket enabled for cluster-api to work. We shifted to use SNO and now we don't require it anymore.
- https://github.com/openshift/installer/tree/master/docs/dev/libvirt#configure-libvirt-to-accept-tcp-connections
> Stop accessing libvirt over unauthenticated qemu+tcp connection 

- snc.sh
Since we switched from libvirt IPI to SNO where platform is used as
`none` so the image registry operator bootstraps itself as Removed.
Which means registry operator not start the registry instance and any
configurations are ignored. Since registry operator not started that
means there is no registry route and user not able to push image to
internal registry and get following error.
```
podman login -u kubeadmin -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing --tls-verify=false` we get an error:
Error: authenticating creds for "default-route-openshift-image-registry.apps-crc.testing": pinging container registry default-route-openshift-image-registry.apps-crc.testing: received unexpected HTTP status: 503 Service Unavailable
```
- …
> Change managementState of Image Registry Operator config from Removed to Managed

- createdisk-library.sh
https://issues.redhat.com/browse/OCPBUGS-11437 is now fixed which means we no longer need to use the workaround to update .orig file of pull secret to have it replace with a dummy one.
> [release-4.16] Remove hack around MCO .orig file

- build-patched-kao-kcmo-images.sh
- snc.sh
Since 4.15 is released and bundles are shipped but looks like we forgot to update the mirror url.
> Update mirror url from `ocp-dev-preview` to `ocp`

- microshift.sh
- repos/mirror-microshift.repo
- snc.sh
4.16 bits now available as release candidate to mirror.openshift.com under `ocp` location instead `ocp-dev-preview`.
> 4.16: Update Mirror url from `ocp-dev-preview` to `ocp`

- build-patched-kao-kcmo-images.sh
4fdb1443d7c24e173497a18198ba20cae202a7d0 hardcode the image name instead using the variable, this patch will fix it.
> kao-kcmo-images.sh: Don't hardcode the image name

- createdisk-library.sh
- createdisk.sh
We already put warning around 3 release before for crc side that macOS < 13 is not supported and try to update the os. With this PR, kernel downgrade logic is removed which is required for macos<13.
Bundle created using this PR will not work for macos less than 13.x.
- https://github.com/crc-org/crc/pull/4029
> Remove kernel downgrade logic for vfkit bundles

- createdisk-library.sh
- createdisk.sh
We already put warning around 3 release before for crc side that macOS < 13 is not supported and try to update the os. With this PR, kernel downgrade logic is removed which is required for macos<13.
Bundle created using this PR will not work for macos less than 13.x.
- https://github.com/crc-org/crc/pull/4029
Manual cherry-picked because it failed automatic https://github.com/crc-org/snc/pull/890#issuecomment-2133349717
> [master] Remove kernel downgrade logic for vfkit bundles

- snc-library.sh
looks like the default oc tarball is built on RHEL9 instead RHEL8 and it cause following issue when running it on RHEL-8
```
oc: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by oc)
```
This patch now explicit use the oc tarball which is built on RHEL8
Fixes: #910
> Use oc binary which is built on RHEL8

- qemu-guest-agent.service
On linux/windows, we don't setup the needed vsock devices, so
qemu-guest-agent fails to start.
We can use `ConditionVirtualization=apple` to only start it when running
on a mac.
> Only use qemu-guest-agent on macos

- build-patched-kao-kcmo-images.sh
This reverts commit 4fdb1443d7c24e173497a18198ba20cae202a7d0.
Revert "kao-kcmo-images.sh: Don't hardcode the image name"
This reverts commit d395f7555af15e9d7b740a62b0437895ff6fcaae.
Revert "kao-kcmo-images.sh: Add reference for `image_from_brew` variable"
This reverts commit a1afbb2ee80c72c22fdf6cc0749bbee8145c3d7a.
We need to revert since the metadata file is not available for quite some time even after the brew build successful and CI is failing because of that with following error.
```
++ curl -L https://download.eng.bos.redhat.com/brewroot/packages/crc-cluster-kube-apiserver-operator-container/v4.15.0/202406052127.p0.geae6926.assembly.stream.el9/metadata.json
++ jq -r '.build.extra.image.index.pull[0]'
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current …
```
> [Master] Revert "build-patched-kao-kcmo-images.sh: get image name from brew container image metadata

- build-patched-kao-kcmo-images.sh
This reverts commit a2b6ece823dfade602a128585e477fbdf6ac56ab.
Revert "kao-kcmo-images.sh: Don't hardcode the image name"
This reverts commit d4ca7af70589d951ec19df5363da52b1757ff307.
Revert "kao-kcmo-images.sh: Add reference for `image_from_brew` variable"
This reverts commit 8c64f2d9e24713c615a92f40376d39f4a0ab23cf.
We need to revert since the metadata file is not available for quite some time even after the brew build successful and CI is failing because of that with following error.
```
++ curl -L https://download.eng.bos.redhat.com/brewroot/packages/crc-cluster-kube-apiserver-operator-container/v4.15.0/202406052127.p0.geae6926.assembly.stream.el9/metadata.json
++ jq -r '.build.extra.image.index.pull[0]'
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current …
```
> [release-4.16]Revert "build-patched-kao-kcmo-images.sh: get image name from brew container image metadata

- ci_microshift.sh
- createdisk.sh
Because of https://issues.redhat.com//browse/OCPBUGS-35468 bug microshift is failed to start and as workaround the value of `listenAddress` should be `null`. It will fix following error
```
Jul 03 04:30:53 api.crc.testing microshift[1933]: ??? I0703 04:30:53.417607    1933 run.go:64] "Version" microshift="4.16.0" base="4.16.0"
Jul 03 04:30:53 api.crc.testing microshift[1933]: ??? E0703 04:30:53.421007    1933 run.go:74] "command failed" err="invalid configuration: error validating ingress.listenAddress: interface  not present in the host
```
Fixes: #928
> Microshift: Use  listenAddress value as null for microshift config

- ci.sh
Currently the artifacts generated by `openshift-tests` are lost when the pipeline finishes, with this change we move it inside the `crc-tmp-install-data` folder so that it gets uploaded to GCS.
> ci.sh: moved test artifacts folder to crc-tmp-install-data

- ci.sh
- ci_microshift.sh
crc moved to use go-1.22 but here it is built using 1.21 and result to an error.
> ci: update go version from 1.21 to 1.22

- ci.sh
- ci_microshift.sh
crc moved to use go-1.22 but here it is built using 1.21 and result to an error.
> [release-4.17]ci: update go version from 1.21 to 1.22

- ci.sh
- ci_microshift.sh
crc moved to use go-1.22 but here it is built using 1.21 and result to an error.
> [release-4.16] ci: update go version from 1.21 to 1.22

- createdisk.sh
Looks like 8.2.4 is deleted https://koji.fedoraproject.org/koji/buildinfo?buildID=2465534 and it cause issue for bundle creation, updating to 8.2.6 https://koji.fedoraproject.org/koji/buildinfo?buildID=2547717
> Update qemu-user-static-x86 to 8.2.6 version

- createdisk.sh
Looks like 8.2.4 is deleted https://koji.fedoraproject.org/koji/buildinfo?buildID=2465534 and it cause issue for bundle creation, updating to 8.2.6 https://koji.fedoraproject.org/koji/buildinfo?buildID=2547717
> [release-4.17] Update qemu-user-static-x86 to 8.2.6 version

- snc-library.sh
OKD scos release doesn't provide the windows artifacts and till now we were using the old 4.14 one which might not work with latest version of OKD. This PR is going to extract it from the specified release.
- https://github.com/okd-project/okd-scos/issues/17
> [OKD] Get the oc tarball for windows using payload

- createdisk-library.sh
Recently on crc side[0] we have enabled the regex to capture bundle info and as part of this regex we are capturing the custom bundle which is random generated number like
`crc_okd_vfkit_4.16.7_amd64_2342465234654.crcbundle` but for bundles generated by the pr have suffix `.pr<pr_number>` which means again adjust the regex. We can still identify the bundle with `_<pr_number>` and this way we don't need to update the regex.
- https://github.com/crc-org/crc/pull/4343
> Update DEST_DIR_SUFFIX in case of pr

- createdisk.sh
> createdisk.sh: enable fedora-updates repo for qemu-user-static-x86

- oauth_cr.yaml
With [1] it was attempted to set token expiration to infinite but as described in [2] with the config set to 0, token expiration is set to default i.e 24 hours. With this patch setting it to a larger value i.e 365 days.
[1] https://github.com/crc-org/snc/pull/332
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1959776
Related-Issue: #331
> Set ouath user token expiration time to 365 days

- crc-bundle-info.json.sample
- createdisk-library.sh
- createdisk.sh
- repos/mirror-microshift.repo
- test-metadata-generation.sh
After https://github.com/crc-org/crc/pull/4309 we don't need to use those references for running the bundle on macOS so better to remove this unused code/reference.
fixes: #992
> Remove initramfs/vmlinuz references for mac bundles

- crc-bundle-info.json.sample
- createdisk-library.sh
- createdisk.sh
- test-metadata-generation.sh
After https://github.com/crc-org/crc/pull/4309 we don't need to use those references for running the bundle on macOS so better to remove this unused code/reference.
fixes: #992
> [release-4.18] Remove initramfs/vmlinuz references for mac bundles

- ci_microshift.sh
4.17 is already released so better to consume whatever available as part of public release instead from mirror which doesn't get updated once public release happen.
> ci_microshift: Remove PRERELEASE flag for 4.17

- 99_master-create-users-symlink.yaml
- snc.sh
As part of `enable-shared-dirs`, in crc codebase we first make it mutable and then create top level directory for mount and again make it immutable. This is we are doing only for Mac because for linux it is $HOME and for windows we are mounting it under `/mnt`. In RHCOS `/home` and `/mnt` is already symlink to `/var/home` and `/var/mnt` which is by default mutable. So for mac we only need `/Users` to be symlink to `/var/Users`. We can remove that code on crc side during shared directories.
Another motivation is as part of `image-mode` base system `chattr` is not going to make system mutable for rootfs and there also we are going to use same workaround (make /Users to symlink to `/var`). This way both the bundle should behave same way.
> Add logic to make filesystem immutable for directory sharing from host

- image-mode/microshift/config/Containerfile.bootc-rhel9
This will allow us to place different scripts which is going to used for self sufficient bundle to `/usr/local/bin` same way it is allowed in the openshift bundles because there also it is symlinked
```
total 136
[...]
lrwxrwxrwx.   2 root root    15 Aug  1  2022 local -> ../var/usrlocal
```
> microshift: Create symlink of /usr/local to make is mutable

- createdisk.sh
When debugging the cert rotation failure found out that because we
remove the network pods so as part of crio cleanup all data around this
pod is also get removed and it can't start. If cert is not
expire this can be again created automatic hence we never had issue but
in case kubelet-serving certs expire then node is not ready and there
is no network config so it become a dead lock since crio started but not
with that config and also openshift started but not able recreate this
config on disk.
> Don't remove network pods from etcd db during cleanup

- image-mode/microshift/build.sh
- image-mode/microshift/config/Containerfile.bootc-rhel9
These are missed during 1fb32f89992b2b56c3ae796a6a11cc0f5a0c74cd
> Renamed USHIFT to MICROSHIFT for variables

- image-mode/microshift/build.sh
By default podman uses the cache to build image and since we are using same node that means cached layer is already exist and old microshift package installed instead of latest one.
> microshift: Use no-cache option for microshift image build
