crc-org/snc

README.md
createdisk.sh
snc.sh

This pull request is a bunch of not really related changes, let me know if you want smaller/more focused PRs, if there are things missing from the logs, ...

Add virt-sparsify call and xz compression to createdisk.sh

---

crc_libvirt.template

Some cleanups I did a while ago, which I'm pushing now since crc_libvirt.sh needed a bugfix.

Misc cleanups in crc_libvirt.sh template

---

createdisk.sh

Update crc-bundle-info.json with vbox disk format

---

createdisk.sh

Disable kubelet service and pull dnsmasq image

---

snc.sh

Most of the developer and user who are working with openshift-4
side need this one to present and this operator itself not talking
as much resources as we anticipated.

Issue #50 Don't disable marketplace operator.

---

createdisk.sh
pull-secret.yaml

We have pull secret part of etcd db which is replaced by an empty
json string `{}` and also remove it from the VM disk side.

Issue #57 Remove pull secret from k8s secret resource

---

crc-bundle-info.json.sample
createdisk.sh

Add disk size, sha256sum, driver info to bundle info file

---

createdisk.sh

Check if the cert is rotated initially and now have 30 days validity.
Exit early in case the rotation doesn't happened yet.

Issue #72 Add check for cert rotation

---

createdisk.sh
htpasswd_cr.yaml

Issue #73 Add an user developer with password developer

---

createdisk.sh
snc.sh

This change will make it easy to search the codeReadyContainer invokers
from the telemeter side.

Issue #90 Add codeReadyContainer as invoker for installer

---

createdisk.sh

OpenShift 4.3 moved their root partition to a LUKS volume so that they
can reencrypt it more easily. One problem this causes is that
virt-sparsify/virt-resize do not deal very well with such partitions
(see 782ace66 "Remove virt-sparsify because of disk encryption" for
example).
This has a bad side-effect: the resulting bundle ends up being more than
4GB, which is far too big.
Another smaller issue is that virt-resize does not call xfs-growfs after
having grown the FS so the root filesystem is not actually bigger.
This commit shrinks the bundle to about 2.3GB by doing manually the same
steps as virt-sparsify after mounting the luks partition. It also calls
xfs-growfs to avoid the issue mentioned above.

Manually sparsify luks partitions

---

createdisk.sh
snc.sh

2 minor fixes to use pre-existing shell variable rather than hardcoding a value.

Minor fixes

---

kubelet-bootstrap-cred-manager-ds.yaml
snc.sh

Main goal was to factor some code/group related code together to make the script easier to follow.
I've compared oc get co/oc get pods before and after these changes and did not notice differences.

Miscellaneous improvements/refactors for snc.sh

---

LICENSE

But the generated bundle/image are not apache licensed
Fixes #170

Issue #170 Add apache 2.0 license

---

createdisk.sh
kubelet-bootstrap-cred-manager-ds.yaml.in

With new version of oc `--config` flag might not even available so
better to update it to `--kubeconfig` flag.

oc flag --config has been deprecated, use --kubeconfig instead

---

snc.sh

With current script when we try to capture the installer image, we
use `echo $OPENSHIFT_PULL_SECRET > pull-secret` which leaks the pull
secret on the CI environment, with this PR we are going to use path
instead of pull secret variable to prevent it.

Use pull secret file path as environment variable

---

cluster-network-03-config.yaml
install-config.yaml
snc.sh

- https://github.com/bbrowning/snc/commit/6d416a5dca837ef2bf42c6269a2010a239caf965

Misc changes to accommodate Ben's changes so bundle can be used as is. 

---

snc.sh

a572aab "Hide the pull secret from stdout" prevents the pull secret from
being shown on stdout, but at the cost of not showing
'${YQ} write --inplace ${INSTALL_DIR}/install-config.yaml pullSecret'
when the script is run with 'set -x' / 'set -o xtrace'.
This commit sets a dummy value in install-config.yaml which is then
replaced with the actual pull secret in a function which makes sure the
pull secret is never shown on stdout.
'set -x' output is now more explicit:
+ cp install-config.yaml crc-tmp-install-data
+ ./yq write --inplace crc-tmp-install-data/install-config.yaml baseDomain testing
+ ./yq write --inplace crc-tmp-install-data/install-config.yaml metadata.name crc
+ ./yq write --inplace crc-tmp-install-data/install-config.yaml 'compute[0].replicas' 0
+ ./yq write --inplace …

Rework hiding of pull secret from stdout

---

createdisk.sh

Newer macos release uses a filesystem which supports sparse files. qcow2
support in hyperkit has known issues, and using it is not recommended. A
sparse raw file should not be much different from a qcow2 file with
respect to disk usage, so we can switch to using this.

Use raw image on macos

---

createdisk.sh

Add support for Hyper-V socket. It does nothing on Linux and macOS but load the module on Windows.

Load hv_sock module

---

crc_libvirt.template
createdisk.sh

The script now properly fails in case of an error in a command.

shell scripts fail on first error

---

README.md

Update README.md to include: 
"Please note the SNC project is “as-is” on this Github repository. At this time, it is not an offically supported Red Hat solution."
Close issue #214

Address Red Hat Support in README

---

createdisk.sh
snc.sh

The most notable one is the 'oc' change, the other really are minor changes.
Let's see what CI thinks about these though as I did not run them locally.

Small snc cleanups

---

createdisk.sh
snc.sh

Modified snc.sh to pull the oc binaries for OKD.
Modified createdisk.sh to install the hyperv driver for Windows from the default FCOS repository for OKD.

Support building an OKD bundle with the oc binary embedded

---

ci.sh
shellcheck.sh

This doesn't fix the error but add the infrastructure to run shellcheck.

Add shellcheck to validate snc.sh and createdisk.sh

---

createdisk.sh

Fixes https://github.com/code-ready/snc/issues/295
It will remove around 300MB of logs uncompressed.

Remove /var/log/*/*.log after all components are stopped

---

createdisk.sh
cvo-overrides-after-first-run.yaml
cvo-overrides.yaml
snc.sh

This is just an update/rebase of #294

Rebased and updated logic for latest 4.7 release bits

---

ci.sh
createdisk-library.sh
createdisk.sh
install-config.yaml
snc-library.sh
snc.sh

I took all master commits except https://github.com/code-ready/snc/pull/310

Prepare 4.6 branch for next release

---

ci.sh
createdisk.sh
snc-library.sh
snc.sh

Lot of changes and patches are applied to the cluster after it
provisioned. This patch will make sure to cluster again become stable
after all those patches/changes.

Use installer wait-for functionality to wait till cluster become stable

---

createdisk.sh

new image pushed to quay.io: https://quay.io/repository/crcont/gvisor-tap-vsock?tab=tags

bump gvisor-tap-vsock container image to v4

---

createdisk.sh

In 4.8 nightly builds, it is observed that the changes for dummy
network not presisted during the reboot. Looking into the networkManager
logs doesn't provide any suspious activity. This patch will create
a systemd unit file which suppose to create the dummy network for
every start.

Use systemd unit file to create dummy network

---

snc.sh

Memory requests with 4.7.0:
Before: 6097Mi (68%)
After:  5697Mi (64%)

Remove more memory requests (400Mi) and second packageserver container

---

createdisk.sh

The feature was added in crc by https://github.com/code-ready/crc/pull/1793
The image digest needs to be sync between both projects.

Preload routes controller image

---

snc.sh

We are exposing registry route `default-route-openshift-image-registry.apps-crc.testing`
for the user to push or pull the images from openshift internal registry
and use it to deploy their application.
Current flow is user login to the registry and push the image to specific namespace.
Then to use it with the application either they need to use internal registry URl
`image-registry.openshift-image-registry.svc:5000` or enable the image-lookup as
mentioned in the doc https://code-ready.github.io/crc/#accessing-the-internal-openshift-registry_gsg
This patch is use the registry route CA and add it to VM so it will not failed with following error in
case of application deployed using this registry.
```
Failed to pull image "default-route-openshift-image-registry.apps-crc.testing/zen/cpd-operat …
```

Add CA cert of exposed registry route to VM

---

snc-library.sh

fix hardcoded api.crc.testing

---

snc.sh

Externalization VM settings through environment variables:
CRC_VM_MEMORY
CRC_VM_CPUS
CRC_VM_DISK_SIZE

Externalization VM settings: memory, vCPUs and disk size.

---

snc-library.sh

snc-library: replace oc with macro ${OC}

---

createdisk.sh

It would help to run the dnsmasq container in case there is a reboot.

Create systemd unit for dnsmasq container

---

createdisk.sh

It is now using DHCP to configure the network card.
---
I need to also bump the vendoring on crc side at the same time.

Bump gvisor-tap-vsock image to latest version

---

createdisk-library.sh
createdisk.sh

This patch allows us to identify podman version as part of crc status.

Add podman version as part of node detail

---

images/openshift-ci/Dockerfile
images/openshift-ci/google-cloud-sdk.repo

This PR rebase CI changes to master branch.

Rebase ci fixes

---

fcos-config.yaml

the file is updated with a random string on each start by crc

read the bearer token from a file instead of using a constant string

---

crc-bundle-info.json.sample
createdisk-library.sh
createdisk.sh

Supersed the #512

---

crc-bundle-info.json.sample
createdisk-library.sh
createdisk.sh
snc-library.sh

Superseed the cherry-pick #513

Superseed the cherry-pick #513 

---

createdisk-library.sh
createdisk.sh
snc-library.sh
snc.sh

This is cherry-pick for #514 in master branch.

Cherry-pick for vfkit bundle generation

---

createdisk-library.sh
createdisk.sh

Since we are now only using vfkit bundles, hyperkit is not required
anymore.

Remove bundle creation for hyperkit

---

createdisk-library.sh
createdisk.sh

This PR reworks the createdisk-library.sh code in snc's master branch.
It should not cause any functional changes.
However, this will get the master branch code closer to the one in the podman branch.
The corresponding changes for the podman branch can be seen in https://github.com/cfergeau/snc/tree/podman , I'll file a PR for these later.

Refactor createdisk-library.sh to make it closer to the one in the podman branch

---

createdisk-library.sh
createdisk.sh
install-config.yaml
snc.sh

Now 4.11 is released and we are start consuming it so better to have our master branch sync with 4.11 branch now and we will create release-4.12 branch for dev purpose (mostly accommodate changes which doesn't affect our master)

Sync master with release-4.11 branch

---

build-patched-kao-kcmo-images.sh

As of now 4.12 is produced as engineering candidate (ec) bits and it is available ocp-dev-preview location. We made change to this patch script to adopt this change and also just create scratch builds instead tag one so that QE can able to hook it with CI.

Update kao-kcmo patch script for 4.12 nightly

---

snc-library.sh

`kubelet-serving` csr is created in few sec after `kube-apiserver-client-kubelet` is approved. Sometime `kubelet-serving` approved automatic but sometime it remain pending and our bundle is created. `kubelet-serving` csr request is responsible for kubelet-server cert and if that remain pending then `kubelet-server` cert is not valid for longer period.
This PR adds another check just to make sure it is approved as soon as created and also add check for cert vailidy for kubelet-server-current certs.

Wait for kubelet-serving signer request also

---

createdisk.sh

We started to create images for dnsmasq and route-controller as part of patched KAO/KCMO images and those images are tagged with openshift version. It is good to tag dnsmasq and route-controller image also with openshift version if present otherwise use latest.

Use openshift version as image tag for dnsmasq/route-controller if presnt

---

build-patched-kao-kcmo-images.sh
cvo-overrides-after-first-run.yaml
cvo-overrides.yaml
install-config.yaml
snc.sh

This pr is rebase of release-4.12 branch on master.

Rebase release-4.12 to master

---

createdisk-library.sh
createdisk.sh
tools.sh

This PR makes sure the config.json.mcdorig file created by the MCO is in sync
with the config.json which we added to the bundle disk image during the
creation process. This file may contain credentials so we need to make sure
it's empty.

Sync config.json.mcdorig file with bundle content

---

build-patched-kao-kcmo-images.sh
microshift.sh
snc.sh

Merge release_4.13 branch to master, there is some conflicts which resolved manually and merge commit is https://github.com/crc-org/snc/pull/725/commits/cc921435929fd7e3782b3dce0dccf069eaf4c115 one.

Merge release_4.13 branch to master

---

build-patched-kao-kcmo-images.sh

Recently there was issue with brew and jobs are stuck to `free` state for a day and after that it succeed but our jenkins jobs fails to wait that long and when we rebuild the job since KAO image already built on the brew it will not fetch the repo and routes and dnsmasq images never built for that specific version of openshift.
This PR make sure we always built those images as long as the `From` section from Dockerfile changes.

Build crc-dnsmasq and crc-route-controller image even KAO image already present

---

microshift.sh

- https://github.com/crc-org/snc/pull/790#discussion_r1295823156
- https://github.com/crc-org/snc/pull/787/files#r1295831946

Misc: update microshift.sh as per some PR review suggestions

---

microshift.sh

- https://github.com/crc-org/snc/pull/790#discussion_r1295823156
- https://github.com/crc-org/snc/pull/787/files#r1295831946

[release-4.14] Misc: update microshift.sh as per some PR review suggestions

---

build-patched-kao-kcmo-images.sh

Since 4.15 switch to rhel-9 content even for base images so we also need to switch rhel-9 for our patched images.
This is just replacement of #860 (not sure why rebase is not working on that).

[master] build-patched-kao-kcmo-images.sh: use rhel-9 branch to build images

---

createdisk-library.sh
microshift.sh

A few commits were not cherry-picked from 4.15 to master, I don't think this
was intentional.

Sync master with release-4.15 branch

---

build-patched-kao-kcmo-images.sh
ci.sh
ci_microshift.sh
microshift.sh
repos/mirror-microshift.repo
snc.sh

cherry-picked from https://github.com/crc-org/snc/pull/872

[release-4.16] microshift script related changes to update it to 4.16

---

createdisk-library.sh

Per #868
This basically reverts the (quick fix) change.

remove hardcoded podman binary version

---

build-patched-kao-kcmo-images.sh

build-patched-kao-kcmo-images.sh: get image name from brew container image metadata

---

install-config.yaml

[4.16.0] Install-config: Add Ingress to enable as part of capability

---

snc.sh

Use `oc adm prune renderedmachineconfigs` to remove older machine configs

---

kubevirt-hostpath-provisioner-csi/csi-driver/kustomization.yaml

- https://catalog.redhat.com/software/containers/container-native-virtualization/hostpath-csi-driver-rhel9/633ffadaa13cf60c13cf6474

csi-driver: Update hostpath-csi-driver tag to 4.15

---

createdisk.sh

snc is still using an old f37 version, let's use something newer than
that.

aarch64: Update qemu-user-static

---

ci.sh

disable monitor tests

---

tools.sh

Increasing the number of retries should help with various issues during setup (i.e. waiting for cert renewal, getting pods...).

tools.sh: increased number of retries

---

createdisk.sh

As of now when user consume the bundle to provision the cluster, old data around pods and lease is consumed and timestamp for those pods are also around same time when we first provisioned this cluster. This PR try to use etcd image to run etcd server using same db which created by the cluster  and uses etcdctl command to delete the pods and lease details. It will help to make sure every pods comes up in clean state.

Delete pods and lease using etcd container

---

ci.sh

ci.sh: moved test artifacts folder to crc-tmp-install-data

---

ci.sh
ci_microshift.sh

ci: update golang version to go1.23

---

oauth_cr.yaml
snc.sh

the current patch is failing to be applied
with version 4.19.0-ec.1

remove tip in login page about crc credentials 
